# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .local_state_reference import *
from .provider import *
from .remote_state_reference import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[]
""",
    resource_packages="""
[
 {
  "pkg": "terraform",
  "token": "pulumi:providers:terraform",
  "fqn": "pulumi_terraform",
  "class": "Provider"
 }
]
"""
)
