# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'LocalStateReferenceResult',
    'AwaitableLocalStateReferenceResult',
    'local_state_reference',
    'local_state_reference_output',
]

@pulumi.output_type
class LocalStateReferenceResult:
    """
    The result of fetching from a Terraform state store.
    """
    def __init__(__self__, outputs=None):
        if outputs and not isinstance(outputs, dict):
            raise TypeError("Expected argument 'outputs' to be a dict")
        pulumi.set(__self__, "outputs", outputs)

    @property
    @pulumi.getter
    def outputs(self) -> Mapping[str, Any]:
        """
        The outputs displayed from Terraform state.
        """
        return pulumi.get(self, "outputs")


class AwaitableLocalStateReferenceResult(LocalStateReferenceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return LocalStateReferenceResult(
            outputs=self.outputs)


def local_state_reference(path: Optional[str] = None,
                          workspace_dir: Optional[str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableLocalStateReferenceResult:
    """
    Access state from the local filesystem.


    :param str path: The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
    :param str workspace_dir: The path to non-default workspaces.
    """
    __args__ = dict()
    __args__['path'] = path
    __args__['workspaceDir'] = workspace_dir
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('terraform:index:localStateReference', __args__, opts=opts, typ=LocalStateReferenceResult).value

    return AwaitableLocalStateReferenceResult(
        outputs=pulumi.get(__ret__, 'outputs'))
def local_state_reference_output(path: Optional[pulumi.Input[Optional[str]]] = None,
                                 workspace_dir: Optional[pulumi.Input[Optional[str]]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[LocalStateReferenceResult]:
    """
    Access state from the local filesystem.


    :param str path: The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
    :param str workspace_dir: The path to non-default workspaces.
    """
    __args__ = dict()
    __args__['path'] = path
    __args__['workspaceDir'] = workspace_dir
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('terraform:index:localStateReference', __args__, opts=opts, typ=LocalStateReferenceResult)
    return __ret__.apply(lambda __response__: LocalStateReferenceResult(
        outputs=pulumi.get(__response__, 'outputs')))
