// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package terraform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform/sdk/go/terraform/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type BackendConfig struct {
	Hostname     *string `pulumi:"hostname"`
	Organization string  `pulumi:"organization"`
	ResourceName *string `pulumi:"resourceName"`
	Token        string  `pulumi:"token"`
}

// BackendConfigInput is an input type that accepts BackendConfigArgs and BackendConfigOutput values.
// You can construct a concrete instance of `BackendConfigInput` via:
//
//	BackendConfigArgs{...}
type BackendConfigInput interface {
	pulumi.Input

	ToBackendConfigOutput() BackendConfigOutput
	ToBackendConfigOutputWithContext(context.Context) BackendConfigOutput
}

type BackendConfigArgs struct {
	Hostname     pulumi.StringPtrInput `pulumi:"hostname"`
	Organization pulumi.StringInput    `pulumi:"organization"`
	ResourceName pulumi.StringPtrInput `pulumi:"resourceName"`
	Token        pulumi.StringInput    `pulumi:"token"`
}

func (BackendConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BackendConfig)(nil)).Elem()
}

func (i BackendConfigArgs) ToBackendConfigOutput() BackendConfigOutput {
	return i.ToBackendConfigOutputWithContext(context.Background())
}

func (i BackendConfigArgs) ToBackendConfigOutputWithContext(ctx context.Context) BackendConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BackendConfigOutput)
}

type BackendConfigOutput struct{ *pulumi.OutputState }

func (BackendConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BackendConfig)(nil)).Elem()
}

func (o BackendConfigOutput) ToBackendConfigOutput() BackendConfigOutput {
	return o
}

func (o BackendConfigOutput) ToBackendConfigOutputWithContext(ctx context.Context) BackendConfigOutput {
	return o
}

func (o BackendConfigOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BackendConfig) *string { return v.Hostname }).(pulumi.StringPtrOutput)
}

func (o BackendConfigOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v BackendConfig) string { return v.Organization }).(pulumi.StringOutput)
}

func (o BackendConfigOutput) ResourceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BackendConfig) *string { return v.ResourceName }).(pulumi.StringPtrOutput)
}

func (o BackendConfigOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v BackendConfig) string { return v.Token }).(pulumi.StringOutput)
}

type WorkspaceStateArgs struct {
	Name   *string `pulumi:"name"`
	Prefix *string `pulumi:"prefix"`
}

// WorkspaceStateArgsInput is an input type that accepts WorkspaceStateArgsArgs and WorkspaceStateArgsOutput values.
// You can construct a concrete instance of `WorkspaceStateArgsInput` via:
//
//	WorkspaceStateArgsArgs{...}
type WorkspaceStateArgsInput interface {
	pulumi.Input

	ToWorkspaceStateArgsOutput() WorkspaceStateArgsOutput
	ToWorkspaceStateArgsOutputWithContext(context.Context) WorkspaceStateArgsOutput
}

type WorkspaceStateArgsArgs struct {
	Name   pulumi.StringPtrInput `pulumi:"name"`
	Prefix pulumi.StringPtrInput `pulumi:"prefix"`
}

func (WorkspaceStateArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WorkspaceStateArgs)(nil)).Elem()
}

func (i WorkspaceStateArgsArgs) ToWorkspaceStateArgsOutput() WorkspaceStateArgsOutput {
	return i.ToWorkspaceStateArgsOutputWithContext(context.Background())
}

func (i WorkspaceStateArgsArgs) ToWorkspaceStateArgsOutputWithContext(ctx context.Context) WorkspaceStateArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkspaceStateArgsOutput)
}

type WorkspaceStateArgsOutput struct{ *pulumi.OutputState }

func (WorkspaceStateArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WorkspaceStateArgs)(nil)).Elem()
}

func (o WorkspaceStateArgsOutput) ToWorkspaceStateArgsOutput() WorkspaceStateArgsOutput {
	return o
}

func (o WorkspaceStateArgsOutput) ToWorkspaceStateArgsOutputWithContext(ctx context.Context) WorkspaceStateArgsOutput {
	return o
}

func (o WorkspaceStateArgsOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WorkspaceStateArgs) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o WorkspaceStateArgsOutput) Prefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WorkspaceStateArgs) *string { return v.Prefix }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BackendConfigInput)(nil)).Elem(), BackendConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkspaceStateArgsInput)(nil)).Elem(), WorkspaceStateArgsArgs{})
	pulumi.RegisterOutputType(BackendConfigOutput{})
	pulumi.RegisterOutputType(WorkspaceStateArgsOutput{})
}
