// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package terraform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform/sdk/v6/go/terraform/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Workspaces struct {
	// The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
	Name *string `pulumi:"name"`
	// A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in HCP Terraform, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
	Prefix *string `pulumi:"prefix"`
}

// WorkspacesInput is an input type that accepts WorkspacesArgs and WorkspacesOutput values.
// You can construct a concrete instance of `WorkspacesInput` via:
//
//	WorkspacesArgs{...}
type WorkspacesInput interface {
	pulumi.Input

	ToWorkspacesOutput() WorkspacesOutput
	ToWorkspacesOutputWithContext(context.Context) WorkspacesOutput
}

type WorkspacesArgs struct {
	// The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in HCP Terraform, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
	Prefix pulumi.StringPtrInput `pulumi:"prefix"`
}

func (WorkspacesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Workspaces)(nil)).Elem()
}

func (i WorkspacesArgs) ToWorkspacesOutput() WorkspacesOutput {
	return i.ToWorkspacesOutputWithContext(context.Background())
}

func (i WorkspacesArgs) ToWorkspacesOutputWithContext(ctx context.Context) WorkspacesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkspacesOutput)
}

type WorkspacesOutput struct{ *pulumi.OutputState }

func (WorkspacesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Workspaces)(nil)).Elem()
}

func (o WorkspacesOutput) ToWorkspacesOutput() WorkspacesOutput {
	return o
}

func (o WorkspacesOutput) ToWorkspacesOutputWithContext(ctx context.Context) WorkspacesOutput {
	return o
}

// The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
func (o WorkspacesOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Workspaces) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in HCP Terraform, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
func (o WorkspacesOutput) Prefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Workspaces) *string { return v.Prefix }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkspacesInput)(nil)).Elem(), WorkspacesArgs{})
	pulumi.RegisterOutputType(WorkspacesOutput{})
}
