template: native
provider: terraform
major-version: 6
pulumiVersionFile: .pulumi.version
providerDefaultBranch: master
parallel: 3
modulePath: .
envOverride:
    PULUMI_API: https://api.pulumi-staging.io
    TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
    TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
