archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
blobs:
- bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-west-2
builds:
- binary: pulumi-resource-terraform
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ignore: []
  ldflags:
  - -X github.com/pulumi/pulumi-terraform/provider/v5/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-terraform/
changelog:
  filters:
    exclude:
    - Merge branch
    - Merge pull request
    - \Winternal\W
    - \Wci\W
    - \Wchore\W
  sort: asc
  use: git
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
