[[constraint]]
  name = "github.com/pulumi/pulumi"
  version = "v0.15.1"

# Redirect all Terraform references to our fork.
[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"
