// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LocalStateReferenceArgs extends com.pulumi.resources.InvokeArgs {

    public static final LocalStateReferenceArgs Empty = new LocalStateReferenceArgs();

    /**
     * The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
     * 
     */
    @Import(name="path")
    private @Nullable Output<String> path;

    /**
     * @return The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
     * 
     */
    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * The path to non-default workspaces.
     * 
     */
    @Import(name="workspaceDir")
    private @Nullable Output<String> workspaceDir;

    /**
     * @return The path to non-default workspaces.
     * 
     */
    public Optional<Output<String>> workspaceDir() {
        return Optional.ofNullable(this.workspaceDir);
    }

    private LocalStateReferenceArgs() {}

    private LocalStateReferenceArgs(LocalStateReferenceArgs $) {
        this.path = $.path;
        this.workspaceDir = $.workspaceDir;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LocalStateReferenceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LocalStateReferenceArgs $;

        public Builder() {
            $ = new LocalStateReferenceArgs();
        }

        public Builder(LocalStateReferenceArgs defaults) {
            $ = new LocalStateReferenceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param path The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
         * 
         * @return builder
         * 
         */
        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @param path The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        /**
         * @param workspaceDir The path to non-default workspaces.
         * 
         * @return builder
         * 
         */
        public Builder workspaceDir(@Nullable Output<String> workspaceDir) {
            $.workspaceDir = workspaceDir;
            return this;
        }

        /**
         * @param workspaceDir The path to non-default workspaces.
         * 
         * @return builder
         * 
         */
        public Builder workspaceDir(String workspaceDir) {
            return workspaceDir(Output.of(workspaceDir));
        }

        public LocalStateReferenceArgs build() {
            return $;
        }
    }

}
