// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Terraform
{
    public static class LocalStateReference
    {
        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Task<LocalStateReferenceResult> InvokeAsync(LocalStateReferenceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LocalStateReferenceResult>("terraform:index:localStateReference", args ?? new LocalStateReferenceArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Output<LocalStateReferenceResult> Invoke(LocalStateReferenceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LocalStateReferenceResult>("terraform:index:localStateReference", args ?? new LocalStateReferenceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Output<LocalStateReferenceResult> Invoke(LocalStateReferenceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<LocalStateReferenceResult>("terraform:index:localStateReference", args ?? new LocalStateReferenceInvokeArgs(), options.WithDefaults());
    }


    public sealed class LocalStateReferenceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
        /// </summary>
        [Input("path")]
        public string? Path { get; set; }

        /// <summary>
        /// The path to non-default workspaces.
        /// </summary>
        [Input("workspaceDir")]
        public string? WorkspaceDir { get; set; }

        public LocalStateReferenceArgs()
        {
        }
        public static new LocalStateReferenceArgs Empty => new LocalStateReferenceArgs();
    }

    public sealed class LocalStateReferenceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// The path to non-default workspaces.
        /// </summary>
        [Input("workspaceDir")]
        public Input<string>? WorkspaceDir { get; set; }

        public LocalStateReferenceInvokeArgs()
        {
        }
        public static new LocalStateReferenceInvokeArgs Empty => new LocalStateReferenceInvokeArgs();
    }


    [OutputType]
    public sealed class LocalStateReferenceResult
    {
        /// <summary>
        /// The outputs displayed from Terraform state.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Outputs;

        [OutputConstructor]
        private LocalStateReferenceResult(ImmutableDictionary<string, object> outputs)
        {
            Outputs = outputs;
        }
    }
}
