// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Terraform
{
    public static class RemoteStateReference
    {
        /// <summary>
        /// Access state from a remote backend.
        /// </summary>
        public static Task<RemoteStateReferenceResult> InvokeAsync(RemoteStateReferenceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<RemoteStateReferenceResult>("terraform:index:remoteStateReference", args ?? new RemoteStateReferenceArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from a remote backend.
        /// </summary>
        public static Output<RemoteStateReferenceResult> Invoke(RemoteStateReferenceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<RemoteStateReferenceResult>("terraform:index:remoteStateReference", args ?? new RemoteStateReferenceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from a remote backend.
        /// </summary>
        public static Output<RemoteStateReferenceResult> Invoke(RemoteStateReferenceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<RemoteStateReferenceResult>("terraform:index:remoteStateReference", args ?? new RemoteStateReferenceInvokeArgs(), options.WithDefaults());
    }


    public sealed class RemoteStateReferenceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The remote backend hostname to connect to.
        /// </summary>
        [Input("hostname")]
        public string? Hostname { get; set; }

        /// <summary>
        /// The name of the organization containing the targeted workspace(s).
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        /// <summary>
        /// The token used to authenticate with the remote backend.
        /// </summary>
        [Input("token")]
        public string? Token { get; set; }

        [Input("workspaces", required: true)]
        public Inputs.Workspaces Workspaces { get; set; } = null!;

        public RemoteStateReferenceArgs()
        {
            Hostname = "app.terraform.io";
        }
        public static new RemoteStateReferenceArgs Empty => new RemoteStateReferenceArgs();
    }

    public sealed class RemoteStateReferenceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The remote backend hostname to connect to.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The name of the organization containing the targeted workspace(s).
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// The token used to authenticate with the remote backend.
        /// </summary>
        [Input("token")]
        public Input<string>? Token { get; set; }

        [Input("workspaces", required: true)]
        public Input<Inputs.WorkspacesArgs> Workspaces { get; set; } = null!;

        public RemoteStateReferenceInvokeArgs()
        {
            Hostname = "app.terraform.io";
        }
        public static new RemoteStateReferenceInvokeArgs Empty => new RemoteStateReferenceInvokeArgs();
    }


    [OutputType]
    public sealed class RemoteStateReferenceResult
    {
        /// <summary>
        /// The outputs displayed from Terraform state.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Outputs;

        [OutputConstructor]
        private RemoteStateReferenceResult(ImmutableDictionary<string, object> outputs)
        {
            Outputs = outputs;
        }
    }
}
