// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package state

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform/sdk/v6/go/terraform/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Access state stored in an Azure Blob Storage container.
func GetAzureRMReference(ctx *pulumi.Context, args *GetAzureRMReferenceArgs, opts ...pulumi.InvokeOption) (*GetAzureRMReferenceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAzureRMReferenceResult
	err := ctx.Invoke("terraform:state:getAzureRMReference", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAzureRMReferenceArgs struct {
	// The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
	AccessKey *string `pulumi:"accessKey"`
	// The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
	ClientCertificatePassword *string `pulumi:"clientCertificatePassword"`
	// The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
	ClientCertificatePath *string `pulumi:"clientCertificatePath"`
	// The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
	ClientId *string `pulumi:"clientId"`
	// The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
	ClientSecret *string `pulumi:"clientSecret"`
	// The name of the storage container within the storage account.
	ContainerName string `pulumi:"containerName"`
	// A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
	Endpoint *string `pulumi:"endpoint"`
	// The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
	Environment *string `pulumi:"environment"`
	// The name of the blob holding the Terraform state file inside the storage container.
	Key string `pulumi:"key"`
	// The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
	MetadataHost *string `pulumi:"metadataHost"`
	// The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
	MsiEndpoint *string `pulumi:"msiEndpoint"`
	// The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
	OidcRequestToken *string `pulumi:"oidcRequestToken"`
	// The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
	OidcRequestUrl *string `pulumi:"oidcRequestUrl"`
	// A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
	OidcToken *string `pulumi:"oidcToken"`
	// The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
	OidcTokenFilePath *string `pulumi:"oidcTokenFilePath"`
	// The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
	ResourceGroupName *string `pulumi:"resourceGroupName"`
	// A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
	SasToken *string `pulumi:"sasToken"`
	// The name of the storage account.
	StorageAccountName string `pulumi:"storageAccountName"`
	// The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
	SubscriptionId *string `pulumi:"subscriptionId"`
	// The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
	TenantId *string `pulumi:"tenantId"`
	// Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
	UseAzureadAuth *bool `pulumi:"useAzureadAuth"`
	// Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
	UseMsi *bool `pulumi:"useMsi"`
	// Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
	UseOidc *bool `pulumi:"useOidc"`
	// The Terraform workspace to read state from.
	Workspace *string `pulumi:"workspace"`
}

// Defaults sets the appropriate defaults for GetAzureRMReferenceArgs
func (val *GetAzureRMReferenceArgs) Defaults() *GetAzureRMReferenceArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Workspace == nil {
		workspace_ := "default"
		tmp.Workspace = &workspace_
	}
	return &tmp
}

// The result of fetching from a Terraform state store.
type GetAzureRMReferenceResult struct {
	// The outputs displayed from Terraform state.
	Outputs map[string]interface{} `pulumi:"outputs"`
}

func GetAzureRMReferenceOutput(ctx *pulumi.Context, args GetAzureRMReferenceOutputArgs, opts ...pulumi.InvokeOption) GetAzureRMReferenceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAzureRMReferenceResultOutput, error) {
			args := v.(GetAzureRMReferenceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("terraform:state:getAzureRMReference", args.Defaults(), GetAzureRMReferenceResultOutput{}, options).(GetAzureRMReferenceResultOutput), nil
		}).(GetAzureRMReferenceResultOutput)
}

type GetAzureRMReferenceOutputArgs struct {
	// The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
	AccessKey pulumi.StringPtrInput `pulumi:"accessKey"`
	// The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
	ClientCertificatePassword pulumi.StringPtrInput `pulumi:"clientCertificatePassword"`
	// The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
	ClientCertificatePath pulumi.StringPtrInput `pulumi:"clientCertificatePath"`
	// The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
	ClientId pulumi.StringPtrInput `pulumi:"clientId"`
	// The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
	ClientSecret pulumi.StringPtrInput `pulumi:"clientSecret"`
	// The name of the storage container within the storage account.
	ContainerName pulumi.StringInput `pulumi:"containerName"`
	// A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
	Endpoint pulumi.StringPtrInput `pulumi:"endpoint"`
	// The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
	Environment pulumi.StringPtrInput `pulumi:"environment"`
	// The name of the blob holding the Terraform state file inside the storage container.
	Key pulumi.StringInput `pulumi:"key"`
	// The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
	MetadataHost pulumi.StringPtrInput `pulumi:"metadataHost"`
	// The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
	MsiEndpoint pulumi.StringPtrInput `pulumi:"msiEndpoint"`
	// The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
	OidcRequestToken pulumi.StringPtrInput `pulumi:"oidcRequestToken"`
	// The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
	OidcRequestUrl pulumi.StringPtrInput `pulumi:"oidcRequestUrl"`
	// A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
	OidcToken pulumi.StringPtrInput `pulumi:"oidcToken"`
	// The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
	OidcTokenFilePath pulumi.StringPtrInput `pulumi:"oidcTokenFilePath"`
	// The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
	ResourceGroupName pulumi.StringPtrInput `pulumi:"resourceGroupName"`
	// A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
	SasToken pulumi.StringPtrInput `pulumi:"sasToken"`
	// The name of the storage account.
	StorageAccountName pulumi.StringInput `pulumi:"storageAccountName"`
	// The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
	SubscriptionId pulumi.StringPtrInput `pulumi:"subscriptionId"`
	// The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
	TenantId pulumi.StringPtrInput `pulumi:"tenantId"`
	// Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
	UseAzureadAuth pulumi.BoolPtrInput `pulumi:"useAzureadAuth"`
	// Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
	UseMsi pulumi.BoolPtrInput `pulumi:"useMsi"`
	// Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
	UseOidc pulumi.BoolPtrInput `pulumi:"useOidc"`
	// The Terraform workspace to read state from.
	Workspace pulumi.StringPtrInput `pulumi:"workspace"`
}

func (GetAzureRMReferenceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAzureRMReferenceArgs)(nil)).Elem()
}

// The result of fetching from a Terraform state store.
type GetAzureRMReferenceResultOutput struct{ *pulumi.OutputState }

func (GetAzureRMReferenceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAzureRMReferenceResult)(nil)).Elem()
}

func (o GetAzureRMReferenceResultOutput) ToGetAzureRMReferenceResultOutput() GetAzureRMReferenceResultOutput {
	return o
}

func (o GetAzureRMReferenceResultOutput) ToGetAzureRMReferenceResultOutputWithContext(ctx context.Context) GetAzureRMReferenceResultOutput {
	return o
}

// The outputs displayed from Terraform state.
func (o GetAzureRMReferenceResultOutput) Outputs() pulumi.MapOutput {
	return o.ApplyT(func(v GetAzureRMReferenceResult) map[string]interface{} { return v.Outputs }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAzureRMReferenceResultOutput{})
}
