// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package state

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform/sdk/v6/go/terraform/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Access state from the local filesystem.
func GetLocalReference(ctx *pulumi.Context, args *GetLocalReferenceArgs, opts ...pulumi.InvokeOption) (*GetLocalReferenceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLocalReferenceResult
	err := ctx.Invoke("terraform:state:getLocalReference", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetLocalReferenceArgs struct {
	// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
	Path *string `pulumi:"path"`
	// The path to non-default workspaces.
	WorkspaceDir *string `pulumi:"workspaceDir"`
}

// The result of fetching from a Terraform state store.
type GetLocalReferenceResult struct {
	// The outputs displayed from Terraform state.
	Outputs map[string]interface{} `pulumi:"outputs"`
}

func GetLocalReferenceOutput(ctx *pulumi.Context, args GetLocalReferenceOutputArgs, opts ...pulumi.InvokeOption) GetLocalReferenceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLocalReferenceResultOutput, error) {
			args := v.(GetLocalReferenceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("terraform:state:getLocalReference", args, GetLocalReferenceResultOutput{}, options).(GetLocalReferenceResultOutput), nil
		}).(GetLocalReferenceResultOutput)
}

type GetLocalReferenceOutputArgs struct {
	// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
	Path pulumi.StringPtrInput `pulumi:"path"`
	// The path to non-default workspaces.
	WorkspaceDir pulumi.StringPtrInput `pulumi:"workspaceDir"`
}

func (GetLocalReferenceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLocalReferenceArgs)(nil)).Elem()
}

// The result of fetching from a Terraform state store.
type GetLocalReferenceResultOutput struct{ *pulumi.OutputState }

func (GetLocalReferenceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLocalReferenceResult)(nil)).Elem()
}

func (o GetLocalReferenceResultOutput) ToGetLocalReferenceResultOutput() GetLocalReferenceResultOutput {
	return o
}

func (o GetLocalReferenceResultOutput) ToGetLocalReferenceResultOutputWithContext(ctx context.Context) GetLocalReferenceResultOutput {
	return o
}

// The outputs displayed from Terraform state.
func (o GetLocalReferenceResultOutput) Outputs() pulumi.MapOutput {
	return o.ApplyT(func(v GetLocalReferenceResult) map[string]interface{} { return v.Outputs }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLocalReferenceResultOutput{})
}
