// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package state

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform/sdk/v6/go/terraform/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Access state from an AWS S3 bucket.
func GetS3Reference(ctx *pulumi.Context, args *GetS3ReferenceArgs, opts ...pulumi.InvokeOption) (*GetS3ReferenceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetS3ReferenceResult
	err := ctx.Invoke("terraform:state:getS3Reference", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetS3ReferenceArgs struct {
	// AWS access key.
	AccessKey *string `pulumi:"accessKey"`
	// The name of the S3 bucket.
	Bucket string `pulumi:"bucket"`
	// Whether to enable server side encryption of the state file.
	Encrypt *bool `pulumi:"encrypt"`
	// A custom endpoint for the S3 API.
	Endpoint *string `pulumi:"endpoint"`
	// Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
	ForcePathStyle *bool `pulumi:"forcePathStyle"`
	// A custom endpoint for the IAM API.
	IamEndpoint *string `pulumi:"iamEndpoint"`
	// The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
	Key string `pulumi:"key"`
	// The ARN of a KMS Key to use for encrypting the state.
	KmsKeyId *string `pulumi:"kmsKeyId"`
	// The maximum number of times an AWS API request is retried on retryable failure.
	MaxRetries *int `pulumi:"maxRetries"`
	// AWS profile name as set in the shared credentials file.
	Profile *string `pulumi:"profile"`
	// AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
	Region *string `pulumi:"region"`
	// AWS secret key.
	SecretKey *string `pulumi:"secretKey"`
	// Path to a shared credentials file.
	SharedCredentialsFile *string `pulumi:"sharedCredentialsFile"`
	// Skip the credentials validation via the STS API.
	SkipCredentialsValidation *bool `pulumi:"skipCredentialsValidation"`
	// Skip the AWS Metadata API check.
	SkipMetadataApiCheck *bool `pulumi:"skipMetadataApiCheck"`
	// Skip static validation of region name.
	SkipRegionValidation *bool `pulumi:"skipRegionValidation"`
	// The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
	SseCustomerKey *string `pulumi:"sseCustomerKey"`
	// A custom endpoint for the STS API.
	StsEndpoint *string `pulumi:"stsEndpoint"`
	// AWS session token.
	Token *string `pulumi:"token"`
	// The Terraform workspace to read state from.
	Workspace *string `pulumi:"workspace"`
	// The prefix applied to the non-default state path inside the bucket.
	WorkspaceKeyPrefix *string `pulumi:"workspaceKeyPrefix"`
}

// Defaults sets the appropriate defaults for GetS3ReferenceArgs
func (val *GetS3ReferenceArgs) Defaults() *GetS3ReferenceArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Workspace == nil {
		workspace_ := "default"
		tmp.Workspace = &workspace_
	}
	return &tmp
}

// The result of fetching from a Terraform state store.
type GetS3ReferenceResult struct {
	// The outputs displayed from Terraform state.
	Outputs map[string]interface{} `pulumi:"outputs"`
}

func GetS3ReferenceOutput(ctx *pulumi.Context, args GetS3ReferenceOutputArgs, opts ...pulumi.InvokeOption) GetS3ReferenceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetS3ReferenceResultOutput, error) {
			args := v.(GetS3ReferenceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("terraform:state:getS3Reference", args.Defaults(), GetS3ReferenceResultOutput{}, options).(GetS3ReferenceResultOutput), nil
		}).(GetS3ReferenceResultOutput)
}

type GetS3ReferenceOutputArgs struct {
	// AWS access key.
	AccessKey pulumi.StringPtrInput `pulumi:"accessKey"`
	// The name of the S3 bucket.
	Bucket pulumi.StringInput `pulumi:"bucket"`
	// Whether to enable server side encryption of the state file.
	Encrypt pulumi.BoolPtrInput `pulumi:"encrypt"`
	// A custom endpoint for the S3 API.
	Endpoint pulumi.StringPtrInput `pulumi:"endpoint"`
	// Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
	ForcePathStyle pulumi.BoolPtrInput `pulumi:"forcePathStyle"`
	// A custom endpoint for the IAM API.
	IamEndpoint pulumi.StringPtrInput `pulumi:"iamEndpoint"`
	// The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
	Key pulumi.StringInput `pulumi:"key"`
	// The ARN of a KMS Key to use for encrypting the state.
	KmsKeyId pulumi.StringPtrInput `pulumi:"kmsKeyId"`
	// The maximum number of times an AWS API request is retried on retryable failure.
	MaxRetries pulumi.IntPtrInput `pulumi:"maxRetries"`
	// AWS profile name as set in the shared credentials file.
	Profile pulumi.StringPtrInput `pulumi:"profile"`
	// AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
	Region pulumi.StringPtrInput `pulumi:"region"`
	// AWS secret key.
	SecretKey pulumi.StringPtrInput `pulumi:"secretKey"`
	// Path to a shared credentials file.
	SharedCredentialsFile pulumi.StringPtrInput `pulumi:"sharedCredentialsFile"`
	// Skip the credentials validation via the STS API.
	SkipCredentialsValidation pulumi.BoolPtrInput `pulumi:"skipCredentialsValidation"`
	// Skip the AWS Metadata API check.
	SkipMetadataApiCheck pulumi.BoolPtrInput `pulumi:"skipMetadataApiCheck"`
	// Skip static validation of region name.
	SkipRegionValidation pulumi.BoolPtrInput `pulumi:"skipRegionValidation"`
	// The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
	SseCustomerKey pulumi.StringPtrInput `pulumi:"sseCustomerKey"`
	// A custom endpoint for the STS API.
	StsEndpoint pulumi.StringPtrInput `pulumi:"stsEndpoint"`
	// AWS session token.
	Token pulumi.StringPtrInput `pulumi:"token"`
	// The Terraform workspace to read state from.
	Workspace pulumi.StringPtrInput `pulumi:"workspace"`
	// The prefix applied to the non-default state path inside the bucket.
	WorkspaceKeyPrefix pulumi.StringPtrInput `pulumi:"workspaceKeyPrefix"`
}

func (GetS3ReferenceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetS3ReferenceArgs)(nil)).Elem()
}

// The result of fetching from a Terraform state store.
type GetS3ReferenceResultOutput struct{ *pulumi.OutputState }

func (GetS3ReferenceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetS3ReferenceResult)(nil)).Elem()
}

func (o GetS3ReferenceResultOutput) ToGetS3ReferenceResultOutput() GetS3ReferenceResultOutput {
	return o
}

func (o GetS3ReferenceResultOutput) ToGetS3ReferenceResultOutputWithContext(ctx context.Context) GetS3ReferenceResultOutput {
	return o
}

// The outputs displayed from Terraform state.
func (o GetS3ReferenceResultOutput) Outputs() pulumi.MapOutput {
	return o.ApplyT(func(v GetS3ReferenceResult) map[string]interface{} { return v.Outputs }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetS3ReferenceResultOutput{})
}
