// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAzureRMReferencePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAzureRMReferencePlainArgs Empty = new GetAzureRMReferencePlainArgs();

    /**
     * The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
     * 
     */
    @Import(name="accessKey")
    private @Nullable String accessKey;

    /**
     * @return The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
     * 
     */
    public Optional<String> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
     * 
     */
    @Import(name="clientCertificatePassword")
    private @Nullable String clientCertificatePassword;

    /**
     * @return The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
     * 
     */
    public Optional<String> clientCertificatePassword() {
        return Optional.ofNullable(this.clientCertificatePassword);
    }

    /**
     * The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
     * 
     */
    @Import(name="clientCertificatePath")
    private @Nullable String clientCertificatePath;

    /**
     * @return The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
     * 
     */
    public Optional<String> clientCertificatePath() {
        return Optional.ofNullable(this.clientCertificatePath);
    }

    /**
     * The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
     * 
     */
    @Import(name="clientId")
    private @Nullable String clientId;

    /**
     * @return The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
     * 
     */
    public Optional<String> clientId() {
        return Optional.ofNullable(this.clientId);
    }

    /**
     * The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
     * 
     */
    @Import(name="clientSecret")
    private @Nullable String clientSecret;

    /**
     * @return The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
     * 
     */
    public Optional<String> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }

    /**
     * The name of the storage container within the storage account.
     * 
     */
    @Import(name="containerName", required=true)
    private String containerName;

    /**
     * @return The name of the storage container within the storage account.
     * 
     */
    public String containerName() {
        return this.containerName;
    }

    /**
     * A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
     * 
     */
    @Import(name="endpoint")
    private @Nullable String endpoint;

    /**
     * @return A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
     * 
     */
    public Optional<String> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
     * 
     */
    @Import(name="environment")
    private @Nullable String environment;

    /**
     * @return The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
     * 
     */
    public Optional<String> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * The name of the blob holding the Terraform state file inside the storage container.
     * 
     */
    @Import(name="key", required=true)
    private String key;

    /**
     * @return The name of the blob holding the Terraform state file inside the storage container.
     * 
     */
    public String key() {
        return this.key;
    }

    /**
     * The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
     * 
     */
    @Import(name="metadataHost")
    private @Nullable String metadataHost;

    /**
     * @return The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
     * 
     */
    public Optional<String> metadataHost() {
        return Optional.ofNullable(this.metadataHost);
    }

    /**
     * The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
     * 
     */
    @Import(name="msiEndpoint")
    private @Nullable String msiEndpoint;

    /**
     * @return The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
     * 
     */
    public Optional<String> msiEndpoint() {
        return Optional.ofNullable(this.msiEndpoint);
    }

    /**
     * The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
     * 
     */
    @Import(name="oidcRequestToken")
    private @Nullable String oidcRequestToken;

    /**
     * @return The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
     * 
     */
    public Optional<String> oidcRequestToken() {
        return Optional.ofNullable(this.oidcRequestToken);
    }

    /**
     * The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
     * 
     */
    @Import(name="oidcRequestUrl")
    private @Nullable String oidcRequestUrl;

    /**
     * @return The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
     * 
     */
    public Optional<String> oidcRequestUrl() {
        return Optional.ofNullable(this.oidcRequestUrl);
    }

    /**
     * A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
     * 
     */
    @Import(name="oidcToken")
    private @Nullable String oidcToken;

    /**
     * @return A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
     * 
     */
    public Optional<String> oidcToken() {
        return Optional.ofNullable(this.oidcToken);
    }

    /**
     * The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
     * 
     */
    @Import(name="oidcTokenFilePath")
    private @Nullable String oidcTokenFilePath;

    /**
     * @return The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
     * 
     */
    public Optional<String> oidcTokenFilePath() {
        return Optional.ofNullable(this.oidcTokenFilePath);
    }

    /**
     * The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
     * 
     */
    @Import(name="resourceGroupName")
    private @Nullable String resourceGroupName;

    /**
     * @return The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
     * 
     */
    public Optional<String> resourceGroupName() {
        return Optional.ofNullable(this.resourceGroupName);
    }

    /**
     * A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
     * 
     */
    @Import(name="sasToken")
    private @Nullable String sasToken;

    /**
     * @return A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
     * 
     */
    public Optional<String> sasToken() {
        return Optional.ofNullable(this.sasToken);
    }

    /**
     * The name of the storage account.
     * 
     */
    @Import(name="storageAccountName", required=true)
    private String storageAccountName;

    /**
     * @return The name of the storage account.
     * 
     */
    public String storageAccountName() {
        return this.storageAccountName;
    }

    /**
     * The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
     * 
     */
    @Import(name="subscriptionId")
    private @Nullable String subscriptionId;

    /**
     * @return The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
     * 
     */
    public Optional<String> subscriptionId() {
        return Optional.ofNullable(this.subscriptionId);
    }

    /**
     * The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
     * 
     */
    @Import(name="tenantId")
    private @Nullable String tenantId;

    /**
     * @return The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
     * 
     */
    public Optional<String> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    /**
     * Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
     * 
     */
    @Import(name="useAzureadAuth")
    private @Nullable Boolean useAzureadAuth;

    /**
     * @return Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
     * 
     */
    public Optional<Boolean> useAzureadAuth() {
        return Optional.ofNullable(this.useAzureadAuth);
    }

    /**
     * Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
     * 
     */
    @Import(name="useMsi")
    private @Nullable Boolean useMsi;

    /**
     * @return Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
     * 
     */
    public Optional<Boolean> useMsi() {
        return Optional.ofNullable(this.useMsi);
    }

    /**
     * Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
     * 
     */
    @Import(name="useOidc")
    private @Nullable Boolean useOidc;

    /**
     * @return Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
     * 
     */
    public Optional<Boolean> useOidc() {
        return Optional.ofNullable(this.useOidc);
    }

    /**
     * The Terraform workspace to read state from.
     * 
     */
    @Import(name="workspace")
    private @Nullable String workspace;

    /**
     * @return The Terraform workspace to read state from.
     * 
     */
    public Optional<String> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    private GetAzureRMReferencePlainArgs() {}

    private GetAzureRMReferencePlainArgs(GetAzureRMReferencePlainArgs $) {
        this.accessKey = $.accessKey;
        this.clientCertificatePassword = $.clientCertificatePassword;
        this.clientCertificatePath = $.clientCertificatePath;
        this.clientId = $.clientId;
        this.clientSecret = $.clientSecret;
        this.containerName = $.containerName;
        this.endpoint = $.endpoint;
        this.environment = $.environment;
        this.key = $.key;
        this.metadataHost = $.metadataHost;
        this.msiEndpoint = $.msiEndpoint;
        this.oidcRequestToken = $.oidcRequestToken;
        this.oidcRequestUrl = $.oidcRequestUrl;
        this.oidcToken = $.oidcToken;
        this.oidcTokenFilePath = $.oidcTokenFilePath;
        this.resourceGroupName = $.resourceGroupName;
        this.sasToken = $.sasToken;
        this.storageAccountName = $.storageAccountName;
        this.subscriptionId = $.subscriptionId;
        this.tenantId = $.tenantId;
        this.useAzureadAuth = $.useAzureadAuth;
        this.useMsi = $.useMsi;
        this.useOidc = $.useOidc;
        this.workspace = $.workspace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAzureRMReferencePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAzureRMReferencePlainArgs $;

        public Builder() {
            $ = new GetAzureRMReferencePlainArgs();
        }

        public Builder(GetAzureRMReferencePlainArgs defaults) {
            $ = new GetAzureRMReferencePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable String accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param clientCertificatePassword The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder clientCertificatePassword(@Nullable String clientCertificatePassword) {
            $.clientCertificatePassword = clientCertificatePassword;
            return this;
        }

        /**
         * @param clientCertificatePath The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder clientCertificatePath(@Nullable String clientCertificatePath) {
            $.clientCertificatePath = clientCertificatePath;
            return this;
        }

        /**
         * @param clientId The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder clientId(@Nullable String clientId) {
            $.clientId = clientId;
            return this;
        }

        /**
         * @param clientSecret The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder clientSecret(@Nullable String clientSecret) {
            $.clientSecret = clientSecret;
            return this;
        }

        /**
         * @param containerName The name of the storage container within the storage account.
         * 
         * @return builder
         * 
         */
        public Builder containerName(String containerName) {
            $.containerName = containerName;
            return this;
        }

        /**
         * @param endpoint A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable String endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param environment The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder environment(@Nullable String environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param key The name of the blob holding the Terraform state file inside the storage container.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            $.key = key;
            return this;
        }

        /**
         * @param metadataHost The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder metadataHost(@Nullable String metadataHost) {
            $.metadataHost = metadataHost;
            return this;
        }

        /**
         * @param msiEndpoint The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder msiEndpoint(@Nullable String msiEndpoint) {
            $.msiEndpoint = msiEndpoint;
            return this;
        }

        /**
         * @param oidcRequestToken The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
         * 
         * @return builder
         * 
         */
        public Builder oidcRequestToken(@Nullable String oidcRequestToken) {
            $.oidcRequestToken = oidcRequestToken;
            return this;
        }

        /**
         * @param oidcRequestUrl The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
         * 
         * @return builder
         * 
         */
        public Builder oidcRequestUrl(@Nullable String oidcRequestUrl) {
            $.oidcRequestUrl = oidcRequestUrl;
            return this;
        }

        /**
         * @param oidcToken A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder oidcToken(@Nullable String oidcToken) {
            $.oidcToken = oidcToken;
            return this;
        }

        /**
         * @param oidcTokenFilePath The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder oidcTokenFilePath(@Nullable String oidcTokenFilePath) {
            $.oidcTokenFilePath = oidcTokenFilePath;
            return this;
        }

        /**
         * @param resourceGroupName The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
         * 
         * @return builder
         * 
         */
        public Builder resourceGroupName(@Nullable String resourceGroupName) {
            $.resourceGroupName = resourceGroupName;
            return this;
        }

        /**
         * @param sasToken A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder sasToken(@Nullable String sasToken) {
            $.sasToken = sasToken;
            return this;
        }

        /**
         * @param storageAccountName The name of the storage account.
         * 
         * @return builder
         * 
         */
        public Builder storageAccountName(String storageAccountName) {
            $.storageAccountName = storageAccountName;
            return this;
        }

        /**
         * @param subscriptionId The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionId(@Nullable String subscriptionId) {
            $.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * @param tenantId The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder tenantId(@Nullable String tenantId) {
            $.tenantId = tenantId;
            return this;
        }

        /**
         * @param useAzureadAuth Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder useAzureadAuth(@Nullable Boolean useAzureadAuth) {
            $.useAzureadAuth = useAzureadAuth;
            return this;
        }

        /**
         * @param useMsi Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder useMsi(@Nullable Boolean useMsi) {
            $.useMsi = useMsi;
            return this;
        }

        /**
         * @param useOidc Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
         * 
         * @return builder
         * 
         */
        public Builder useOidc(@Nullable Boolean useOidc) {
            $.useOidc = useOidc;
            return this;
        }

        /**
         * @param workspace The Terraform workspace to read state from.
         * 
         * @return builder
         * 
         */
        public Builder workspace(@Nullable String workspace) {
            $.workspace = workspace;
            return this;
        }

        public GetAzureRMReferencePlainArgs build() {
            if ($.containerName == null) {
                throw new MissingRequiredPropertyException("GetAzureRMReferencePlainArgs", "containerName");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetAzureRMReferencePlainArgs", "key");
            }
            if ($.storageAccountName == null) {
                throw new MissingRequiredPropertyException("GetAzureRMReferencePlainArgs", "storageAccountName");
            }
            $.workspace = Codegen.stringProp("workspace").arg($.workspace).def("default").getNullable();
            return $;
        }
    }

}
