// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetLocalReferencePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetLocalReferencePlainArgs Empty = new GetLocalReferencePlainArgs();

    /**
     * The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
     * 
     */
    @Import(name="path")
    private @Nullable String path;

    /**
     * @return The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
     * 
     */
    public Optional<String> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * The path to non-default workspaces.
     * 
     */
    @Import(name="workspaceDir")
    private @Nullable String workspaceDir;

    /**
     * @return The path to non-default workspaces.
     * 
     */
    public Optional<String> workspaceDir() {
        return Optional.ofNullable(this.workspaceDir);
    }

    private GetLocalReferencePlainArgs() {}

    private GetLocalReferencePlainArgs(GetLocalReferencePlainArgs $) {
        this.path = $.path;
        this.workspaceDir = $.workspaceDir;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetLocalReferencePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetLocalReferencePlainArgs $;

        public Builder() {
            $ = new GetLocalReferencePlainArgs();
        }

        public Builder(GetLocalReferencePlainArgs defaults) {
            $ = new GetLocalReferencePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param path The path to the tfstate file. This defaults to &#34;terraform.tfstate&#34; relative to the root module by default.
         * 
         * @return builder
         * 
         */
        public Builder path(@Nullable String path) {
            $.path = path;
            return this;
        }

        /**
         * @param workspaceDir The path to non-default workspaces.
         * 
         * @return builder
         * 
         */
        public Builder workspaceDir(@Nullable String workspaceDir) {
            $.workspaceDir = workspaceDir;
            return this;
        }

        public GetLocalReferencePlainArgs build() {
            return $;
        }
    }

}
