// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.terraform.state.inputs.Workspaces;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRemoteReferencePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRemoteReferencePlainArgs Empty = new GetRemoteReferencePlainArgs();

    /**
     * The remote backend hostname to connect to.
     * 
     */
    @Import(name="hostname")
    private @Nullable String hostname;

    /**
     * @return The remote backend hostname to connect to.
     * 
     */
    public Optional<String> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    /**
     * The name of the organization containing the targeted workspace(s).
     * 
     */
    @Import(name="organization", required=true)
    private String organization;

    /**
     * @return The name of the organization containing the targeted workspace(s).
     * 
     */
    public String organization() {
        return this.organization;
    }

    /**
     * The token used to authenticate with the remote backend.
     * 
     */
    @Import(name="token")
    private @Nullable String token;

    /**
     * @return The token used to authenticate with the remote backend.
     * 
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    @Import(name="workspaces", required=true)
    private Workspaces workspaces;

    public Workspaces workspaces() {
        return this.workspaces;
    }

    private GetRemoteReferencePlainArgs() {}

    private GetRemoteReferencePlainArgs(GetRemoteReferencePlainArgs $) {
        this.hostname = $.hostname;
        this.organization = $.organization;
        this.token = $.token;
        this.workspaces = $.workspaces;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRemoteReferencePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRemoteReferencePlainArgs $;

        public Builder() {
            $ = new GetRemoteReferencePlainArgs();
        }

        public Builder(GetRemoteReferencePlainArgs defaults) {
            $ = new GetRemoteReferencePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param hostname The remote backend hostname to connect to.
         * 
         * @return builder
         * 
         */
        public Builder hostname(@Nullable String hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param organization The name of the organization containing the targeted workspace(s).
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param token The token used to authenticate with the remote backend.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable String token) {
            $.token = token;
            return this;
        }

        public Builder workspaces(Workspaces workspaces) {
            $.workspaces = workspaces;
            return this;
        }

        public GetRemoteReferencePlainArgs build() {
            $.hostname = Codegen.stringProp("hostname").arg($.hostname).def("app.terraform.io").getNullable();
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("GetRemoteReferencePlainArgs", "organization");
            }
            if ($.workspaces == null) {
                throw new MissingRequiredPropertyException("GetRemoteReferencePlainArgs", "workspaces");
            }
            return $;
        }
    }

}
