// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetS3ReferenceArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetS3ReferenceArgs Empty = new GetS3ReferenceArgs();

    /**
     * AWS access key.
     * 
     */
    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    /**
     * @return AWS access key.
     * 
     */
    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * The name of the S3 bucket.
     * 
     */
    @Import(name="bucket", required=true)
    private Output<String> bucket;

    /**
     * @return The name of the S3 bucket.
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }

    /**
     * Whether to enable server side encryption of the state file.
     * 
     */
    @Import(name="encrypt")
    private @Nullable Output<Boolean> encrypt;

    /**
     * @return Whether to enable server side encryption of the state file.
     * 
     */
    public Optional<Output<Boolean>> encrypt() {
        return Optional.ofNullable(this.encrypt);
    }

    /**
     * A custom endpoint for the S3 API.
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return A custom endpoint for the S3 API.
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     * 
     */
    @Import(name="forcePathStyle")
    private @Nullable Output<Boolean> forcePathStyle;

    /**
     * @return Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     * 
     */
    public Optional<Output<Boolean>> forcePathStyle() {
        return Optional.ofNullable(this.forcePathStyle);
    }

    /**
     * A custom endpoint for the IAM API.
     * 
     */
    @Import(name="iamEndpoint")
    private @Nullable Output<String> iamEndpoint;

    /**
     * @return A custom endpoint for the IAM API.
     * 
     */
    public Optional<Output<String>> iamEndpoint() {
        return Optional.ofNullable(this.iamEndpoint);
    }

    /**
     * The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     * 
     */
    @Import(name="key", required=true)
    private Output<String> key;

    /**
     * @return The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     * The ARN of a KMS Key to use for encrypting the state.
     * 
     */
    @Import(name="kmsKeyId")
    private @Nullable Output<String> kmsKeyId;

    /**
     * @return The ARN of a KMS Key to use for encrypting the state.
     * 
     */
    public Optional<Output<String>> kmsKeyId() {
        return Optional.ofNullable(this.kmsKeyId);
    }

    /**
     * The maximum number of times an AWS API request is retried on retryable failure.
     * 
     */
    @Import(name="maxRetries")
    private @Nullable Output<Integer> maxRetries;

    /**
     * @return The maximum number of times an AWS API request is retried on retryable failure.
     * 
     */
    public Optional<Output<Integer>> maxRetries() {
        return Optional.ofNullable(this.maxRetries);
    }

    /**
     * AWS profile name as set in the shared credentials file.
     * 
     */
    @Import(name="profile")
    private @Nullable Output<String> profile;

    /**
     * @return AWS profile name as set in the shared credentials file.
     * 
     */
    public Optional<Output<String>> profile() {
        return Optional.ofNullable(this.profile);
    }

    /**
     * AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * AWS secret key.
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return AWS secret key.
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * Path to a shared credentials file.
     * 
     */
    @Import(name="sharedCredentialsFile")
    private @Nullable Output<String> sharedCredentialsFile;

    /**
     * @return Path to a shared credentials file.
     * 
     */
    public Optional<Output<String>> sharedCredentialsFile() {
        return Optional.ofNullable(this.sharedCredentialsFile);
    }

    /**
     * Skip the credentials validation via the STS API.
     * 
     */
    @Import(name="skipCredentialsValidation")
    private @Nullable Output<Boolean> skipCredentialsValidation;

    /**
     * @return Skip the credentials validation via the STS API.
     * 
     */
    public Optional<Output<Boolean>> skipCredentialsValidation() {
        return Optional.ofNullable(this.skipCredentialsValidation);
    }

    /**
     * Skip the AWS Metadata API check.
     * 
     */
    @Import(name="skipMetadataApiCheck")
    private @Nullable Output<Boolean> skipMetadataApiCheck;

    /**
     * @return Skip the AWS Metadata API check.
     * 
     */
    public Optional<Output<Boolean>> skipMetadataApiCheck() {
        return Optional.ofNullable(this.skipMetadataApiCheck);
    }

    /**
     * Skip static validation of region name.
     * 
     */
    @Import(name="skipRegionValidation")
    private @Nullable Output<Boolean> skipRegionValidation;

    /**
     * @return Skip static validation of region name.
     * 
     */
    public Optional<Output<Boolean>> skipRegionValidation() {
        return Optional.ofNullable(this.skipRegionValidation);
    }

    /**
     * The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     * 
     */
    @Import(name="sseCustomerKey")
    private @Nullable Output<String> sseCustomerKey;

    /**
     * @return The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     * 
     */
    public Optional<Output<String>> sseCustomerKey() {
        return Optional.ofNullable(this.sseCustomerKey);
    }

    /**
     * A custom endpoint for the STS API.
     * 
     */
    @Import(name="stsEndpoint")
    private @Nullable Output<String> stsEndpoint;

    /**
     * @return A custom endpoint for the STS API.
     * 
     */
    public Optional<Output<String>> stsEndpoint() {
        return Optional.ofNullable(this.stsEndpoint);
    }

    /**
     * AWS session token.
     * 
     */
    @Import(name="token")
    private @Nullable Output<String> token;

    /**
     * @return AWS session token.
     * 
     */
    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * The Terraform workspace to read state from.
     * 
     */
    @Import(name="workspace")
    private @Nullable Output<String> workspace;

    /**
     * @return The Terraform workspace to read state from.
     * 
     */
    public Optional<Output<String>> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    /**
     * The prefix applied to the non-default state path inside the bucket.
     * 
     */
    @Import(name="workspaceKeyPrefix")
    private @Nullable Output<String> workspaceKeyPrefix;

    /**
     * @return The prefix applied to the non-default state path inside the bucket.
     * 
     */
    public Optional<Output<String>> workspaceKeyPrefix() {
        return Optional.ofNullable(this.workspaceKeyPrefix);
    }

    private GetS3ReferenceArgs() {}

    private GetS3ReferenceArgs(GetS3ReferenceArgs $) {
        this.accessKey = $.accessKey;
        this.bucket = $.bucket;
        this.encrypt = $.encrypt;
        this.endpoint = $.endpoint;
        this.forcePathStyle = $.forcePathStyle;
        this.iamEndpoint = $.iamEndpoint;
        this.key = $.key;
        this.kmsKeyId = $.kmsKeyId;
        this.maxRetries = $.maxRetries;
        this.profile = $.profile;
        this.region = $.region;
        this.secretKey = $.secretKey;
        this.sharedCredentialsFile = $.sharedCredentialsFile;
        this.skipCredentialsValidation = $.skipCredentialsValidation;
        this.skipMetadataApiCheck = $.skipMetadataApiCheck;
        this.skipRegionValidation = $.skipRegionValidation;
        this.sseCustomerKey = $.sseCustomerKey;
        this.stsEndpoint = $.stsEndpoint;
        this.token = $.token;
        this.workspace = $.workspace;
        this.workspaceKeyPrefix = $.workspaceKeyPrefix;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetS3ReferenceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetS3ReferenceArgs $;

        public Builder() {
            $ = new GetS3ReferenceArgs();
        }

        public Builder(GetS3ReferenceArgs defaults) {
            $ = new GetS3ReferenceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey AWS access key.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param accessKey AWS access key.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        /**
         * @param bucket The name of the S3 bucket.
         * 
         * @return builder
         * 
         */
        public Builder bucket(Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The name of the S3 bucket.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param encrypt Whether to enable server side encryption of the state file.
         * 
         * @return builder
         * 
         */
        public Builder encrypt(@Nullable Output<Boolean> encrypt) {
            $.encrypt = encrypt;
            return this;
        }

        /**
         * @param encrypt Whether to enable server side encryption of the state file.
         * 
         * @return builder
         * 
         */
        public Builder encrypt(Boolean encrypt) {
            return encrypt(Output.of(encrypt));
        }

        /**
         * @param endpoint A custom endpoint for the S3 API.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint A custom endpoint for the S3 API.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param forcePathStyle Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
         * 
         * @return builder
         * 
         */
        public Builder forcePathStyle(@Nullable Output<Boolean> forcePathStyle) {
            $.forcePathStyle = forcePathStyle;
            return this;
        }

        /**
         * @param forcePathStyle Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
         * 
         * @return builder
         * 
         */
        public Builder forcePathStyle(Boolean forcePathStyle) {
            return forcePathStyle(Output.of(forcePathStyle));
        }

        /**
         * @param iamEndpoint A custom endpoint for the IAM API.
         * 
         * @return builder
         * 
         */
        public Builder iamEndpoint(@Nullable Output<String> iamEndpoint) {
            $.iamEndpoint = iamEndpoint;
            return this;
        }

        /**
         * @param iamEndpoint A custom endpoint for the IAM API.
         * 
         * @return builder
         * 
         */
        public Builder iamEndpoint(String iamEndpoint) {
            return iamEndpoint(Output.of(iamEndpoint));
        }

        /**
         * @param key The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
         * 
         * @return builder
         * 
         */
        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param kmsKeyId The ARN of a KMS Key to use for encrypting the state.
         * 
         * @return builder
         * 
         */
        public Builder kmsKeyId(@Nullable Output<String> kmsKeyId) {
            $.kmsKeyId = kmsKeyId;
            return this;
        }

        /**
         * @param kmsKeyId The ARN of a KMS Key to use for encrypting the state.
         * 
         * @return builder
         * 
         */
        public Builder kmsKeyId(String kmsKeyId) {
            return kmsKeyId(Output.of(kmsKeyId));
        }

        /**
         * @param maxRetries The maximum number of times an AWS API request is retried on retryable failure.
         * 
         * @return builder
         * 
         */
        public Builder maxRetries(@Nullable Output<Integer> maxRetries) {
            $.maxRetries = maxRetries;
            return this;
        }

        /**
         * @param maxRetries The maximum number of times an AWS API request is retried on retryable failure.
         * 
         * @return builder
         * 
         */
        public Builder maxRetries(Integer maxRetries) {
            return maxRetries(Output.of(maxRetries));
        }

        /**
         * @param profile AWS profile name as set in the shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder profile(@Nullable Output<String> profile) {
            $.profile = profile;
            return this;
        }

        /**
         * @param profile AWS profile name as set in the shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder profile(String profile) {
            return profile(Output.of(profile));
        }

        /**
         * @param region AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param secretKey AWS secret key.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey AWS secret key.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param sharedCredentialsFile Path to a shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder sharedCredentialsFile(@Nullable Output<String> sharedCredentialsFile) {
            $.sharedCredentialsFile = sharedCredentialsFile;
            return this;
        }

        /**
         * @param sharedCredentialsFile Path to a shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder sharedCredentialsFile(String sharedCredentialsFile) {
            return sharedCredentialsFile(Output.of(sharedCredentialsFile));
        }

        /**
         * @param skipCredentialsValidation Skip the credentials validation via the STS API.
         * 
         * @return builder
         * 
         */
        public Builder skipCredentialsValidation(@Nullable Output<Boolean> skipCredentialsValidation) {
            $.skipCredentialsValidation = skipCredentialsValidation;
            return this;
        }

        /**
         * @param skipCredentialsValidation Skip the credentials validation via the STS API.
         * 
         * @return builder
         * 
         */
        public Builder skipCredentialsValidation(Boolean skipCredentialsValidation) {
            return skipCredentialsValidation(Output.of(skipCredentialsValidation));
        }

        /**
         * @param skipMetadataApiCheck Skip the AWS Metadata API check.
         * 
         * @return builder
         * 
         */
        public Builder skipMetadataApiCheck(@Nullable Output<Boolean> skipMetadataApiCheck) {
            $.skipMetadataApiCheck = skipMetadataApiCheck;
            return this;
        }

        /**
         * @param skipMetadataApiCheck Skip the AWS Metadata API check.
         * 
         * @return builder
         * 
         */
        public Builder skipMetadataApiCheck(Boolean skipMetadataApiCheck) {
            return skipMetadataApiCheck(Output.of(skipMetadataApiCheck));
        }

        /**
         * @param skipRegionValidation Skip static validation of region name.
         * 
         * @return builder
         * 
         */
        public Builder skipRegionValidation(@Nullable Output<Boolean> skipRegionValidation) {
            $.skipRegionValidation = skipRegionValidation;
            return this;
        }

        /**
         * @param skipRegionValidation Skip static validation of region name.
         * 
         * @return builder
         * 
         */
        public Builder skipRegionValidation(Boolean skipRegionValidation) {
            return skipRegionValidation(Output.of(skipRegionValidation));
        }

        /**
         * @param sseCustomerKey The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
         * 
         * @return builder
         * 
         */
        public Builder sseCustomerKey(@Nullable Output<String> sseCustomerKey) {
            $.sseCustomerKey = sseCustomerKey;
            return this;
        }

        /**
         * @param sseCustomerKey The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
         * 
         * @return builder
         * 
         */
        public Builder sseCustomerKey(String sseCustomerKey) {
            return sseCustomerKey(Output.of(sseCustomerKey));
        }

        /**
         * @param stsEndpoint A custom endpoint for the STS API.
         * 
         * @return builder
         * 
         */
        public Builder stsEndpoint(@Nullable Output<String> stsEndpoint) {
            $.stsEndpoint = stsEndpoint;
            return this;
        }

        /**
         * @param stsEndpoint A custom endpoint for the STS API.
         * 
         * @return builder
         * 
         */
        public Builder stsEndpoint(String stsEndpoint) {
            return stsEndpoint(Output.of(stsEndpoint));
        }

        /**
         * @param token AWS session token.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token AWS session token.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        /**
         * @param workspace The Terraform workspace to read state from.
         * 
         * @return builder
         * 
         */
        public Builder workspace(@Nullable Output<String> workspace) {
            $.workspace = workspace;
            return this;
        }

        /**
         * @param workspace The Terraform workspace to read state from.
         * 
         * @return builder
         * 
         */
        public Builder workspace(String workspace) {
            return workspace(Output.of(workspace));
        }

        /**
         * @param workspaceKeyPrefix The prefix applied to the non-default state path inside the bucket.
         * 
         * @return builder
         * 
         */
        public Builder workspaceKeyPrefix(@Nullable Output<String> workspaceKeyPrefix) {
            $.workspaceKeyPrefix = workspaceKeyPrefix;
            return this;
        }

        /**
         * @param workspaceKeyPrefix The prefix applied to the non-default state path inside the bucket.
         * 
         * @return builder
         * 
         */
        public Builder workspaceKeyPrefix(String workspaceKeyPrefix) {
            return workspaceKeyPrefix(Output.of(workspaceKeyPrefix));
        }

        public GetS3ReferenceArgs build() {
            if ($.bucket == null) {
                throw new MissingRequiredPropertyException("GetS3ReferenceArgs", "bucket");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetS3ReferenceArgs", "key");
            }
            $.workspace = Codegen.stringProp("workspace").output().arg($.workspace).def("default").getNullable();
            return $;
        }
    }

}
