// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetS3ReferencePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetS3ReferencePlainArgs Empty = new GetS3ReferencePlainArgs();

    /**
     * AWS access key.
     * 
     */
    @Import(name="accessKey")
    private @Nullable String accessKey;

    /**
     * @return AWS access key.
     * 
     */
    public Optional<String> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * The name of the S3 bucket.
     * 
     */
    @Import(name="bucket", required=true)
    private String bucket;

    /**
     * @return The name of the S3 bucket.
     * 
     */
    public String bucket() {
        return this.bucket;
    }

    /**
     * Whether to enable server side encryption of the state file.
     * 
     */
    @Import(name="encrypt")
    private @Nullable Boolean encrypt;

    /**
     * @return Whether to enable server side encryption of the state file.
     * 
     */
    public Optional<Boolean> encrypt() {
        return Optional.ofNullable(this.encrypt);
    }

    /**
     * A custom endpoint for the S3 API.
     * 
     */
    @Import(name="endpoint")
    private @Nullable String endpoint;

    /**
     * @return A custom endpoint for the S3 API.
     * 
     */
    public Optional<String> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     * 
     */
    @Import(name="forcePathStyle")
    private @Nullable Boolean forcePathStyle;

    /**
     * @return Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     * 
     */
    public Optional<Boolean> forcePathStyle() {
        return Optional.ofNullable(this.forcePathStyle);
    }

    /**
     * A custom endpoint for the IAM API.
     * 
     */
    @Import(name="iamEndpoint")
    private @Nullable String iamEndpoint;

    /**
     * @return A custom endpoint for the IAM API.
     * 
     */
    public Optional<String> iamEndpoint() {
        return Optional.ofNullable(this.iamEndpoint);
    }

    /**
     * The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     * 
     */
    @Import(name="key", required=true)
    private String key;

    /**
     * @return The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     * 
     */
    public String key() {
        return this.key;
    }

    /**
     * The ARN of a KMS Key to use for encrypting the state.
     * 
     */
    @Import(name="kmsKeyId")
    private @Nullable String kmsKeyId;

    /**
     * @return The ARN of a KMS Key to use for encrypting the state.
     * 
     */
    public Optional<String> kmsKeyId() {
        return Optional.ofNullable(this.kmsKeyId);
    }

    /**
     * The maximum number of times an AWS API request is retried on retryable failure.
     * 
     */
    @Import(name="maxRetries")
    private @Nullable Integer maxRetries;

    /**
     * @return The maximum number of times an AWS API request is retried on retryable failure.
     * 
     */
    public Optional<Integer> maxRetries() {
        return Optional.ofNullable(this.maxRetries);
    }

    /**
     * AWS profile name as set in the shared credentials file.
     * 
     */
    @Import(name="profile")
    private @Nullable String profile;

    /**
     * @return AWS profile name as set in the shared credentials file.
     * 
     */
    public Optional<String> profile() {
        return Optional.ofNullable(this.profile);
    }

    /**
     * AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     * 
     */
    @Import(name="region")
    private @Nullable String region;

    /**
     * @return AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     * 
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * AWS secret key.
     * 
     */
    @Import(name="secretKey")
    private @Nullable String secretKey;

    /**
     * @return AWS secret key.
     * 
     */
    public Optional<String> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * Path to a shared credentials file.
     * 
     */
    @Import(name="sharedCredentialsFile")
    private @Nullable String sharedCredentialsFile;

    /**
     * @return Path to a shared credentials file.
     * 
     */
    public Optional<String> sharedCredentialsFile() {
        return Optional.ofNullable(this.sharedCredentialsFile);
    }

    /**
     * Skip the credentials validation via the STS API.
     * 
     */
    @Import(name="skipCredentialsValidation")
    private @Nullable Boolean skipCredentialsValidation;

    /**
     * @return Skip the credentials validation via the STS API.
     * 
     */
    public Optional<Boolean> skipCredentialsValidation() {
        return Optional.ofNullable(this.skipCredentialsValidation);
    }

    /**
     * Skip the AWS Metadata API check.
     * 
     */
    @Import(name="skipMetadataApiCheck")
    private @Nullable Boolean skipMetadataApiCheck;

    /**
     * @return Skip the AWS Metadata API check.
     * 
     */
    public Optional<Boolean> skipMetadataApiCheck() {
        return Optional.ofNullable(this.skipMetadataApiCheck);
    }

    /**
     * Skip static validation of region name.
     * 
     */
    @Import(name="skipRegionValidation")
    private @Nullable Boolean skipRegionValidation;

    /**
     * @return Skip static validation of region name.
     * 
     */
    public Optional<Boolean> skipRegionValidation() {
        return Optional.ofNullable(this.skipRegionValidation);
    }

    /**
     * The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     * 
     */
    @Import(name="sseCustomerKey")
    private @Nullable String sseCustomerKey;

    /**
     * @return The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     * 
     */
    public Optional<String> sseCustomerKey() {
        return Optional.ofNullable(this.sseCustomerKey);
    }

    /**
     * A custom endpoint for the STS API.
     * 
     */
    @Import(name="stsEndpoint")
    private @Nullable String stsEndpoint;

    /**
     * @return A custom endpoint for the STS API.
     * 
     */
    public Optional<String> stsEndpoint() {
        return Optional.ofNullable(this.stsEndpoint);
    }

    /**
     * AWS session token.
     * 
     */
    @Import(name="token")
    private @Nullable String token;

    /**
     * @return AWS session token.
     * 
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * The Terraform workspace to read state from.
     * 
     */
    @Import(name="workspace")
    private @Nullable String workspace;

    /**
     * @return The Terraform workspace to read state from.
     * 
     */
    public Optional<String> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    /**
     * The prefix applied to the non-default state path inside the bucket.
     * 
     */
    @Import(name="workspaceKeyPrefix")
    private @Nullable String workspaceKeyPrefix;

    /**
     * @return The prefix applied to the non-default state path inside the bucket.
     * 
     */
    public Optional<String> workspaceKeyPrefix() {
        return Optional.ofNullable(this.workspaceKeyPrefix);
    }

    private GetS3ReferencePlainArgs() {}

    private GetS3ReferencePlainArgs(GetS3ReferencePlainArgs $) {
        this.accessKey = $.accessKey;
        this.bucket = $.bucket;
        this.encrypt = $.encrypt;
        this.endpoint = $.endpoint;
        this.forcePathStyle = $.forcePathStyle;
        this.iamEndpoint = $.iamEndpoint;
        this.key = $.key;
        this.kmsKeyId = $.kmsKeyId;
        this.maxRetries = $.maxRetries;
        this.profile = $.profile;
        this.region = $.region;
        this.secretKey = $.secretKey;
        this.sharedCredentialsFile = $.sharedCredentialsFile;
        this.skipCredentialsValidation = $.skipCredentialsValidation;
        this.skipMetadataApiCheck = $.skipMetadataApiCheck;
        this.skipRegionValidation = $.skipRegionValidation;
        this.sseCustomerKey = $.sseCustomerKey;
        this.stsEndpoint = $.stsEndpoint;
        this.token = $.token;
        this.workspace = $.workspace;
        this.workspaceKeyPrefix = $.workspaceKeyPrefix;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetS3ReferencePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetS3ReferencePlainArgs $;

        public Builder() {
            $ = new GetS3ReferencePlainArgs();
        }

        public Builder(GetS3ReferencePlainArgs defaults) {
            $ = new GetS3ReferencePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey AWS access key.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable String accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param bucket The name of the S3 bucket.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param encrypt Whether to enable server side encryption of the state file.
         * 
         * @return builder
         * 
         */
        public Builder encrypt(@Nullable Boolean encrypt) {
            $.encrypt = encrypt;
            return this;
        }

        /**
         * @param endpoint A custom endpoint for the S3 API.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable String endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param forcePathStyle Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
         * 
         * @return builder
         * 
         */
        public Builder forcePathStyle(@Nullable Boolean forcePathStyle) {
            $.forcePathStyle = forcePathStyle;
            return this;
        }

        /**
         * @param iamEndpoint A custom endpoint for the IAM API.
         * 
         * @return builder
         * 
         */
        public Builder iamEndpoint(@Nullable String iamEndpoint) {
            $.iamEndpoint = iamEndpoint;
            return this;
        }

        /**
         * @param key The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            $.key = key;
            return this;
        }

        /**
         * @param kmsKeyId The ARN of a KMS Key to use for encrypting the state.
         * 
         * @return builder
         * 
         */
        public Builder kmsKeyId(@Nullable String kmsKeyId) {
            $.kmsKeyId = kmsKeyId;
            return this;
        }

        /**
         * @param maxRetries The maximum number of times an AWS API request is retried on retryable failure.
         * 
         * @return builder
         * 
         */
        public Builder maxRetries(@Nullable Integer maxRetries) {
            $.maxRetries = maxRetries;
            return this;
        }

        /**
         * @param profile AWS profile name as set in the shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder profile(@Nullable String profile) {
            $.profile = profile;
            return this;
        }

        /**
         * @param region AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable String region) {
            $.region = region;
            return this;
        }

        /**
         * @param secretKey AWS secret key.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable String secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param sharedCredentialsFile Path to a shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder sharedCredentialsFile(@Nullable String sharedCredentialsFile) {
            $.sharedCredentialsFile = sharedCredentialsFile;
            return this;
        }

        /**
         * @param skipCredentialsValidation Skip the credentials validation via the STS API.
         * 
         * @return builder
         * 
         */
        public Builder skipCredentialsValidation(@Nullable Boolean skipCredentialsValidation) {
            $.skipCredentialsValidation = skipCredentialsValidation;
            return this;
        }

        /**
         * @param skipMetadataApiCheck Skip the AWS Metadata API check.
         * 
         * @return builder
         * 
         */
        public Builder skipMetadataApiCheck(@Nullable Boolean skipMetadataApiCheck) {
            $.skipMetadataApiCheck = skipMetadataApiCheck;
            return this;
        }

        /**
         * @param skipRegionValidation Skip static validation of region name.
         * 
         * @return builder
         * 
         */
        public Builder skipRegionValidation(@Nullable Boolean skipRegionValidation) {
            $.skipRegionValidation = skipRegionValidation;
            return this;
        }

        /**
         * @param sseCustomerKey The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
         * 
         * @return builder
         * 
         */
        public Builder sseCustomerKey(@Nullable String sseCustomerKey) {
            $.sseCustomerKey = sseCustomerKey;
            return this;
        }

        /**
         * @param stsEndpoint A custom endpoint for the STS API.
         * 
         * @return builder
         * 
         */
        public Builder stsEndpoint(@Nullable String stsEndpoint) {
            $.stsEndpoint = stsEndpoint;
            return this;
        }

        /**
         * @param token AWS session token.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable String token) {
            $.token = token;
            return this;
        }

        /**
         * @param workspace The Terraform workspace to read state from.
         * 
         * @return builder
         * 
         */
        public Builder workspace(@Nullable String workspace) {
            $.workspace = workspace;
            return this;
        }

        /**
         * @param workspaceKeyPrefix The prefix applied to the non-default state path inside the bucket.
         * 
         * @return builder
         * 
         */
        public Builder workspaceKeyPrefix(@Nullable String workspaceKeyPrefix) {
            $.workspaceKeyPrefix = workspaceKeyPrefix;
            return this;
        }

        public GetS3ReferencePlainArgs build() {
            if ($.bucket == null) {
                throw new MissingRequiredPropertyException("GetS3ReferencePlainArgs", "bucket");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetS3ReferencePlainArgs", "key");
            }
            $.workspace = Codegen.stringProp("workspace").arg($.workspace).def("default").getNullable();
            return $;
        }
    }

}
