# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetAzureRMReferenceResult',
    'AwaitableGetAzureRMReferenceResult',
    'get_azure_rm_reference',
    'get_azure_rm_reference_output',
]

@pulumi.output_type
class GetAzureRMReferenceResult:
    """
    The result of fetching from a Terraform state store.
    """
    def __init__(__self__, outputs=None):
        if outputs and not isinstance(outputs, dict):
            raise TypeError("Expected argument 'outputs' to be a dict")
        pulumi.set(__self__, "outputs", outputs)

    @_builtins.property
    @pulumi.getter
    def outputs(self) -> Mapping[str, Any]:
        """
        The outputs displayed from Terraform state.
        """
        return pulumi.get(self, "outputs")


class AwaitableGetAzureRMReferenceResult(GetAzureRMReferenceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAzureRMReferenceResult(
            outputs=self.outputs)


def get_azure_rm_reference(access_key: Optional[_builtins.str] = None,
                           client_certificate_password: Optional[_builtins.str] = None,
                           client_certificate_path: Optional[_builtins.str] = None,
                           client_id: Optional[_builtins.str] = None,
                           client_secret: Optional[_builtins.str] = None,
                           container_name: Optional[_builtins.str] = None,
                           endpoint: Optional[_builtins.str] = None,
                           environment: Optional[_builtins.str] = None,
                           key: Optional[_builtins.str] = None,
                           metadata_host: Optional[_builtins.str] = None,
                           msi_endpoint: Optional[_builtins.str] = None,
                           oidc_request_token: Optional[_builtins.str] = None,
                           oidc_request_url: Optional[_builtins.str] = None,
                           oidc_token: Optional[_builtins.str] = None,
                           oidc_token_file_path: Optional[_builtins.str] = None,
                           resource_group_name: Optional[_builtins.str] = None,
                           sas_token: Optional[_builtins.str] = None,
                           storage_account_name: Optional[_builtins.str] = None,
                           subscription_id: Optional[_builtins.str] = None,
                           tenant_id: Optional[_builtins.str] = None,
                           use_azuread_auth: Optional[_builtins.bool] = None,
                           use_msi: Optional[_builtins.bool] = None,
                           use_oidc: Optional[_builtins.bool] = None,
                           workspace: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAzureRMReferenceResult:
    """
    Access state stored in an Azure Blob Storage container.

    :param _builtins.str access_key: The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
    :param _builtins.str client_certificate_password: The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
    :param _builtins.str client_certificate_path: The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
    :param _builtins.str client_id: The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
    :param _builtins.str client_secret: The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
    :param _builtins.str container_name: The name of the storage container within the storage account.
    :param _builtins.str endpoint: A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
    :param _builtins.str environment: The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
    :param _builtins.str key: The name of the blob holding the Terraform state file inside the storage container.
    :param _builtins.str metadata_host: The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
    :param _builtins.str msi_endpoint: The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
    :param _builtins.str oidc_request_token: The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
    :param _builtins.str oidc_request_url: The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
    :param _builtins.str oidc_token: A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
    :param _builtins.str oidc_token_file_path: The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
    :param _builtins.str resource_group_name: The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
    :param _builtins.str sas_token: A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
    :param _builtins.str storage_account_name: The name of the storage account.
    :param _builtins.str subscription_id: The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
    :param _builtins.str tenant_id: The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
    :param _builtins.bool use_azuread_auth: Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
    :param _builtins.bool use_msi: Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
    :param _builtins.bool use_oidc: Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
    :param _builtins.str workspace: The Terraform workspace to read state from.
    """
    __args__ = dict()
    __args__['accessKey'] = access_key
    __args__['clientCertificatePassword'] = client_certificate_password
    __args__['clientCertificatePath'] = client_certificate_path
    __args__['clientId'] = client_id
    __args__['clientSecret'] = client_secret
    __args__['containerName'] = container_name
    __args__['endpoint'] = endpoint
    __args__['environment'] = environment
    __args__['key'] = key
    __args__['metadataHost'] = metadata_host
    __args__['msiEndpoint'] = msi_endpoint
    __args__['oidcRequestToken'] = oidc_request_token
    __args__['oidcRequestUrl'] = oidc_request_url
    __args__['oidcToken'] = oidc_token
    __args__['oidcTokenFilePath'] = oidc_token_file_path
    __args__['resourceGroupName'] = resource_group_name
    __args__['sasToken'] = sas_token
    __args__['storageAccountName'] = storage_account_name
    __args__['subscriptionId'] = subscription_id
    __args__['tenantId'] = tenant_id
    __args__['useAzureadAuth'] = use_azuread_auth
    __args__['useMsi'] = use_msi
    __args__['useOidc'] = use_oidc
    __args__['workspace'] = workspace
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('terraform:state:getAzureRMReference', __args__, opts=opts, typ=GetAzureRMReferenceResult).value

    return AwaitableGetAzureRMReferenceResult(
        outputs=pulumi.get(__ret__, 'outputs'))
def get_azure_rm_reference_output(access_key: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  client_certificate_password: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  client_certificate_path: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  client_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  client_secret: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  container_name: pulumi.Input[Optional[_builtins.str]] = None,
                                  endpoint: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  environment: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  key: pulumi.Input[Optional[_builtins.str]] = None,
                                  metadata_host: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  msi_endpoint: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  oidc_request_token: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  oidc_request_url: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  oidc_token: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  oidc_token_file_path: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  resource_group_name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  sas_token: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  storage_account_name: pulumi.Input[Optional[_builtins.str]] = None,
                                  subscription_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  tenant_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  use_azuread_auth: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                                  use_msi: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                                  use_oidc: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                                  workspace: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAzureRMReferenceResult]:
    """
    Access state stored in an Azure Blob Storage container.

    :param _builtins.str access_key: The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
    :param _builtins.str client_certificate_password: The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
    :param _builtins.str client_certificate_path: The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
    :param _builtins.str client_id: The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
    :param _builtins.str client_secret: The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
    :param _builtins.str container_name: The name of the storage container within the storage account.
    :param _builtins.str endpoint: A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
    :param _builtins.str environment: The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
    :param _builtins.str key: The name of the blob holding the Terraform state file inside the storage container.
    :param _builtins.str metadata_host: The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
    :param _builtins.str msi_endpoint: The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
    :param _builtins.str oidc_request_token: The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
    :param _builtins.str oidc_request_url: The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
    :param _builtins.str oidc_token: A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
    :param _builtins.str oidc_token_file_path: The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
    :param _builtins.str resource_group_name: The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
    :param _builtins.str sas_token: A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
    :param _builtins.str storage_account_name: The name of the storage account.
    :param _builtins.str subscription_id: The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
    :param _builtins.str tenant_id: The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
    :param _builtins.bool use_azuread_auth: Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
    :param _builtins.bool use_msi: Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
    :param _builtins.bool use_oidc: Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
    :param _builtins.str workspace: The Terraform workspace to read state from.
    """
    __args__ = dict()
    __args__['accessKey'] = access_key
    __args__['clientCertificatePassword'] = client_certificate_password
    __args__['clientCertificatePath'] = client_certificate_path
    __args__['clientId'] = client_id
    __args__['clientSecret'] = client_secret
    __args__['containerName'] = container_name
    __args__['endpoint'] = endpoint
    __args__['environment'] = environment
    __args__['key'] = key
    __args__['metadataHost'] = metadata_host
    __args__['msiEndpoint'] = msi_endpoint
    __args__['oidcRequestToken'] = oidc_request_token
    __args__['oidcRequestUrl'] = oidc_request_url
    __args__['oidcToken'] = oidc_token
    __args__['oidcTokenFilePath'] = oidc_token_file_path
    __args__['resourceGroupName'] = resource_group_name
    __args__['sasToken'] = sas_token
    __args__['storageAccountName'] = storage_account_name
    __args__['subscriptionId'] = subscription_id
    __args__['tenantId'] = tenant_id
    __args__['useAzureadAuth'] = use_azuread_auth
    __args__['useMsi'] = use_msi
    __args__['useOidc'] = use_oidc
    __args__['workspace'] = workspace
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('terraform:state:getAzureRMReference', __args__, opts=opts, typ=GetAzureRMReferenceResult)
    return __ret__.apply(lambda __response__: GetAzureRMReferenceResult(
        outputs=pulumi.get(__response__, 'outputs')))
