# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetS3ReferenceResult',
    'AwaitableGetS3ReferenceResult',
    'get_s3_reference',
    'get_s3_reference_output',
]

@pulumi.output_type
class GetS3ReferenceResult:
    """
    The result of fetching from a Terraform state store.
    """
    def __init__(__self__, outputs=None):
        if outputs and not isinstance(outputs, dict):
            raise TypeError("Expected argument 'outputs' to be a dict")
        pulumi.set(__self__, "outputs", outputs)

    @_builtins.property
    @pulumi.getter
    def outputs(self) -> Mapping[str, Any]:
        """
        The outputs displayed from Terraform state.
        """
        return pulumi.get(self, "outputs")


class AwaitableGetS3ReferenceResult(GetS3ReferenceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetS3ReferenceResult(
            outputs=self.outputs)


def get_s3_reference(access_key: Optional[_builtins.str] = None,
                     bucket: Optional[_builtins.str] = None,
                     encrypt: Optional[_builtins.bool] = None,
                     endpoint: Optional[_builtins.str] = None,
                     force_path_style: Optional[_builtins.bool] = None,
                     iam_endpoint: Optional[_builtins.str] = None,
                     key: Optional[_builtins.str] = None,
                     kms_key_id: Optional[_builtins.str] = None,
                     max_retries: Optional[_builtins.int] = None,
                     profile: Optional[_builtins.str] = None,
                     region: Optional[_builtins.str] = None,
                     secret_key: Optional[_builtins.str] = None,
                     shared_credentials_file: Optional[_builtins.str] = None,
                     skip_credentials_validation: Optional[_builtins.bool] = None,
                     skip_metadata_api_check: Optional[_builtins.bool] = None,
                     skip_region_validation: Optional[_builtins.bool] = None,
                     sse_customer_key: Optional[_builtins.str] = None,
                     sts_endpoint: Optional[_builtins.str] = None,
                     token: Optional[_builtins.str] = None,
                     workspace: Optional[_builtins.str] = None,
                     workspace_key_prefix: Optional[_builtins.str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetS3ReferenceResult:
    """
    Access state from an AWS S3 bucket.


    :param _builtins.str access_key: AWS access key.
    :param _builtins.str bucket: The name of the S3 bucket.
    :param _builtins.bool encrypt: Whether to enable server side encryption of the state file.
    :param _builtins.str endpoint: A custom endpoint for the S3 API.
    :param _builtins.bool force_path_style: Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
    :param _builtins.str iam_endpoint: A custom endpoint for the IAM API.
    :param _builtins.str key: The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
    :param _builtins.str kms_key_id: The ARN of a KMS Key to use for encrypting the state.
    :param _builtins.int max_retries: The maximum number of times an AWS API request is retried on retryable failure.
    :param _builtins.str profile: AWS profile name as set in the shared credentials file.
    :param _builtins.str region: AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
    :param _builtins.str secret_key: AWS secret key.
    :param _builtins.str shared_credentials_file: Path to a shared credentials file.
    :param _builtins.bool skip_credentials_validation: Skip the credentials validation via the STS API.
    :param _builtins.bool skip_metadata_api_check: Skip the AWS Metadata API check.
    :param _builtins.bool skip_region_validation: Skip static validation of region name.
    :param _builtins.str sse_customer_key: The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
    :param _builtins.str sts_endpoint: A custom endpoint for the STS API.
    :param _builtins.str token: AWS session token.
    :param _builtins.str workspace: The Terraform workspace to read state from.
    :param _builtins.str workspace_key_prefix: The prefix applied to the non-default state path inside the bucket.
    """
    __args__ = dict()
    __args__['accessKey'] = access_key
    __args__['bucket'] = bucket
    __args__['encrypt'] = encrypt
    __args__['endpoint'] = endpoint
    __args__['forcePathStyle'] = force_path_style
    __args__['iamEndpoint'] = iam_endpoint
    __args__['key'] = key
    __args__['kmsKeyId'] = kms_key_id
    __args__['maxRetries'] = max_retries
    __args__['profile'] = profile
    __args__['region'] = region
    __args__['secretKey'] = secret_key
    __args__['sharedCredentialsFile'] = shared_credentials_file
    __args__['skipCredentialsValidation'] = skip_credentials_validation
    __args__['skipMetadataApiCheck'] = skip_metadata_api_check
    __args__['skipRegionValidation'] = skip_region_validation
    __args__['sseCustomerKey'] = sse_customer_key
    __args__['stsEndpoint'] = sts_endpoint
    __args__['token'] = token
    __args__['workspace'] = workspace
    __args__['workspaceKeyPrefix'] = workspace_key_prefix
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('terraform:state:getS3Reference', __args__, opts=opts, typ=GetS3ReferenceResult).value

    return AwaitableGetS3ReferenceResult(
        outputs=pulumi.get(__ret__, 'outputs'))
def get_s3_reference_output(access_key: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            bucket: Optional[pulumi.Input[_builtins.str]] = None,
                            encrypt: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            endpoint: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            force_path_style: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            iam_endpoint: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            key: Optional[pulumi.Input[_builtins.str]] = None,
                            kms_key_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            max_retries: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                            profile: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            secret_key: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            shared_credentials_file: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            skip_credentials_validation: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            skip_metadata_api_check: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            skip_region_validation: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            sse_customer_key: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            sts_endpoint: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            token: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            workspace: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            workspace_key_prefix: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetS3ReferenceResult]:
    """
    Access state from an AWS S3 bucket.


    :param _builtins.str access_key: AWS access key.
    :param _builtins.str bucket: The name of the S3 bucket.
    :param _builtins.bool encrypt: Whether to enable server side encryption of the state file.
    :param _builtins.str endpoint: A custom endpoint for the S3 API.
    :param _builtins.bool force_path_style: Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
    :param _builtins.str iam_endpoint: A custom endpoint for the IAM API.
    :param _builtins.str key: The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
    :param _builtins.str kms_key_id: The ARN of a KMS Key to use for encrypting the state.
    :param _builtins.int max_retries: The maximum number of times an AWS API request is retried on retryable failure.
    :param _builtins.str profile: AWS profile name as set in the shared credentials file.
    :param _builtins.str region: AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
    :param _builtins.str secret_key: AWS secret key.
    :param _builtins.str shared_credentials_file: Path to a shared credentials file.
    :param _builtins.bool skip_credentials_validation: Skip the credentials validation via the STS API.
    :param _builtins.bool skip_metadata_api_check: Skip the AWS Metadata API check.
    :param _builtins.bool skip_region_validation: Skip static validation of region name.
    :param _builtins.str sse_customer_key: The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
    :param _builtins.str sts_endpoint: A custom endpoint for the STS API.
    :param _builtins.str token: AWS session token.
    :param _builtins.str workspace: The Terraform workspace to read state from.
    :param _builtins.str workspace_key_prefix: The prefix applied to the non-default state path inside the bucket.
    """
    __args__ = dict()
    __args__['accessKey'] = access_key
    __args__['bucket'] = bucket
    __args__['encrypt'] = encrypt
    __args__['endpoint'] = endpoint
    __args__['forcePathStyle'] = force_path_style
    __args__['iamEndpoint'] = iam_endpoint
    __args__['key'] = key
    __args__['kmsKeyId'] = kms_key_id
    __args__['maxRetries'] = max_retries
    __args__['profile'] = profile
    __args__['region'] = region
    __args__['secretKey'] = secret_key
    __args__['sharedCredentialsFile'] = shared_credentials_file
    __args__['skipCredentialsValidation'] = skip_credentials_validation
    __args__['skipMetadataApiCheck'] = skip_metadata_api_check
    __args__['skipRegionValidation'] = skip_region_validation
    __args__['sseCustomerKey'] = sse_customer_key
    __args__['stsEndpoint'] = sts_endpoint
    __args__['token'] = token
    __args__['workspace'] = workspace
    __args__['workspaceKeyPrefix'] = workspace_key_prefix
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('terraform:state:getS3Reference', __args__, opts=opts, typ=GetS3ReferenceResult)
    return __ret__.apply(lambda __response__: GetS3ReferenceResult(
        outputs=pulumi.get(__response__, 'outputs')))
