// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetAzureRMReferenceResult {
    /**
     * @return The outputs displayed from Terraform state.
     * 
     */
    private Map<String,Object> outputs;

    private GetAzureRMReferenceResult() {}
    /**
     * @return The outputs displayed from Terraform state.
     * 
     */
    public Map<String,Object> outputs() {
        return this.outputs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAzureRMReferenceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,Object> outputs;
        public Builder() {}
        public Builder(GetAzureRMReferenceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.outputs = defaults.outputs;
        }

        @CustomType.Setter
        public Builder outputs(Map<String,Object> outputs) {
            if (outputs == null) {
              throw new MissingRequiredPropertyException("GetAzureRMReferenceResult", "outputs");
            }
            this.outputs = outputs;
            return this;
        }
        public GetAzureRMReferenceResult build() {
            final var _resultValue = new GetAzureRMReferenceResult();
            _resultValue.outputs = outputs;
            return _resultValue;
        }
    }
}
