// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.terraform.Utilities;
import com.pulumi.terraform.inputs.LocalStateReferenceArgs;
import com.pulumi.terraform.inputs.LocalStateReferencePlainArgs;
import com.pulumi.terraform.inputs.RemoteStateReferenceArgs;
import com.pulumi.terraform.inputs.RemoteStateReferencePlainArgs;
import com.pulumi.terraform.outputs.LocalStateReferenceResult;
import com.pulumi.terraform.outputs.RemoteStateReferenceResult;
import java.util.concurrent.CompletableFuture;

public final class TerraformFunctions {
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<LocalStateReferenceResult> localStateReference() {
        return localStateReference(LocalStateReferenceArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<LocalStateReferenceResult> localStateReferencePlain() {
        return localStateReferencePlain(LocalStateReferencePlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<LocalStateReferenceResult> localStateReference(LocalStateReferenceArgs args) {
        return localStateReference(args, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<LocalStateReferenceResult> localStateReferencePlain(LocalStateReferencePlainArgs args) {
        return localStateReferencePlain(args, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<LocalStateReferenceResult> localStateReference(LocalStateReferenceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("terraform:index:localStateReference", TypeShape.of(LocalStateReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<LocalStateReferenceResult> localStateReference(LocalStateReferenceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("terraform:index:localStateReference", TypeShape.of(LocalStateReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<LocalStateReferenceResult> localStateReferencePlain(LocalStateReferencePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("terraform:index:localStateReference", TypeShape.of(LocalStateReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<RemoteStateReferenceResult> remoteStateReference(RemoteStateReferenceArgs args) {
        return remoteStateReference(args, InvokeOptions.Empty);
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static CompletableFuture<RemoteStateReferenceResult> remoteStateReferencePlain(RemoteStateReferencePlainArgs args) {
        return remoteStateReferencePlain(args, InvokeOptions.Empty);
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<RemoteStateReferenceResult> remoteStateReference(RemoteStateReferenceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("terraform:index:remoteStateReference", TypeShape.of(RemoteStateReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<RemoteStateReferenceResult> remoteStateReference(RemoteStateReferenceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("terraform:index:remoteStateReference", TypeShape.of(RemoteStateReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static CompletableFuture<RemoteStateReferenceResult> remoteStateReferencePlain(RemoteStateReferencePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("terraform:index:remoteStateReference", TypeShape.of(RemoteStateReferenceResult.class), args, Utilities.withVersion(options));
    }
}
