// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Terraform.State
{
    public static class GetAzureRMReference
    {
        /// <summary>
        /// Access state stored in an Azure Blob Storage container.
        /// </summary>
        public static Task<GetAzureRMReferenceResult> InvokeAsync(GetAzureRMReferenceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAzureRMReferenceResult>("terraform:state:getAzureRMReference", args ?? new GetAzureRMReferenceArgs(), options.WithDefaults());

        /// <summary>
        /// Access state stored in an Azure Blob Storage container.
        /// </summary>
        public static Output<GetAzureRMReferenceResult> Invoke(GetAzureRMReferenceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAzureRMReferenceResult>("terraform:state:getAzureRMReference", args ?? new GetAzureRMReferenceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Access state stored in an Azure Blob Storage container.
        /// </summary>
        public static Output<GetAzureRMReferenceResult> Invoke(GetAzureRMReferenceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAzureRMReferenceResult>("terraform:state:getAzureRMReference", args ?? new GetAzureRMReferenceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAzureRMReferenceArgs : global::Pulumi.InvokeArgs
    {
        [Input("accessKey")]
        private string? _accessKey;

        /// <summary>
        /// The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
        /// </summary>
        public string? AccessKey
        {
            get => _accessKey;
            set => _accessKey = value;
        }

        [Input("clientCertificatePassword")]
        private string? _clientCertificatePassword;

        /// <summary>
        /// The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
        /// </summary>
        public string? ClientCertificatePassword
        {
            get => _clientCertificatePassword;
            set => _clientCertificatePassword = value;
        }

        /// <summary>
        /// The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
        /// </summary>
        [Input("clientCertificatePath")]
        public string? ClientCertificatePath { get; set; }

        /// <summary>
        /// The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
        /// </summary>
        [Input("clientId")]
        public string? ClientId { get; set; }

        [Input("clientSecret")]
        private string? _clientSecret;

        /// <summary>
        /// The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
        /// </summary>
        public string? ClientSecret
        {
            get => _clientSecret;
            set => _clientSecret = value;
        }

        /// <summary>
        /// The name of the storage container within the storage account.
        /// </summary>
        [Input("containerName", required: true)]
        public string ContainerName { get; set; } = null!;

        /// <summary>
        /// A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
        /// </summary>
        [Input("endpoint")]
        public string? Endpoint { get; set; }

        /// <summary>
        /// The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
        /// </summary>
        [Input("environment")]
        public string? Environment { get; set; }

        /// <summary>
        /// The name of the blob holding the Terraform state file inside the storage container.
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
        /// </summary>
        [Input("metadataHost")]
        public string? MetadataHost { get; set; }

        /// <summary>
        /// The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
        /// </summary>
        [Input("msiEndpoint")]
        public string? MsiEndpoint { get; set; }

        [Input("oidcRequestToken")]
        private string? _oidcRequestToken;

        /// <summary>
        /// The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
        /// </summary>
        public string? OidcRequestToken
        {
            get => _oidcRequestToken;
            set => _oidcRequestToken = value;
        }

        /// <summary>
        /// The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
        /// </summary>
        [Input("oidcRequestUrl")]
        public string? OidcRequestUrl { get; set; }

        [Input("oidcToken")]
        private string? _oidcToken;

        /// <summary>
        /// A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
        /// </summary>
        public string? OidcToken
        {
            get => _oidcToken;
            set => _oidcToken = value;
        }

        /// <summary>
        /// The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
        /// </summary>
        [Input("oidcTokenFilePath")]
        public string? OidcTokenFilePath { get; set; }

        /// <summary>
        /// The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
        /// </summary>
        [Input("resourceGroupName")]
        public string? ResourceGroupName { get; set; }

        [Input("sasToken")]
        private string? _sasToken;

        /// <summary>
        /// A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
        /// </summary>
        public string? SasToken
        {
            get => _sasToken;
            set => _sasToken = value;
        }

        /// <summary>
        /// The name of the storage account.
        /// </summary>
        [Input("storageAccountName", required: true)]
        public string StorageAccountName { get; set; } = null!;

        /// <summary>
        /// The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
        /// </summary>
        [Input("subscriptionId")]
        public string? SubscriptionId { get; set; }

        /// <summary>
        /// The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
        /// </summary>
        [Input("tenantId")]
        public string? TenantId { get; set; }

        /// <summary>
        /// Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
        /// </summary>
        [Input("useAzureadAuth")]
        public bool? UseAzureadAuth { get; set; }

        /// <summary>
        /// Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
        /// </summary>
        [Input("useMsi")]
        public bool? UseMsi { get; set; }

        /// <summary>
        /// Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
        /// </summary>
        [Input("useOidc")]
        public bool? UseOidc { get; set; }

        /// <summary>
        /// The Terraform workspace to read state from.
        /// </summary>
        [Input("workspace")]
        public string? Workspace { get; set; }

        public GetAzureRMReferenceArgs()
        {
            Workspace = "default";
        }
        public static new GetAzureRMReferenceArgs Empty => new GetAzureRMReferenceArgs();
    }

    public sealed class GetAzureRMReferenceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accessKey")]
        private Input<string>? _accessKey;

        /// <summary>
        /// The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
        /// </summary>
        public Input<string>? AccessKey
        {
            get => _accessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("clientCertificatePassword")]
        private Input<string>? _clientCertificatePassword;

        /// <summary>
        /// The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
        /// </summary>
        public Input<string>? ClientCertificatePassword
        {
            get => _clientCertificatePassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientCertificatePassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
        /// </summary>
        [Input("clientCertificatePath")]
        public Input<string>? ClientCertificatePath { get; set; }

        /// <summary>
        /// The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("clientSecret")]
        private Input<string>? _clientSecret;

        /// <summary>
        /// The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
        /// </summary>
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The name of the storage container within the storage account.
        /// </summary>
        [Input("containerName", required: true)]
        public Input<string> ContainerName { get; set; } = null!;

        /// <summary>
        /// A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The name of the blob holding the Terraform state file inside the storage container.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
        /// </summary>
        [Input("metadataHost")]
        public Input<string>? MetadataHost { get; set; }

        /// <summary>
        /// The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
        /// </summary>
        [Input("msiEndpoint")]
        public Input<string>? MsiEndpoint { get; set; }

        [Input("oidcRequestToken")]
        private Input<string>? _oidcRequestToken;

        /// <summary>
        /// The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
        /// </summary>
        public Input<string>? OidcRequestToken
        {
            get => _oidcRequestToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oidcRequestToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
        /// </summary>
        [Input("oidcRequestUrl")]
        public Input<string>? OidcRequestUrl { get; set; }

        [Input("oidcToken")]
        private Input<string>? _oidcToken;

        /// <summary>
        /// A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
        /// </summary>
        public Input<string>? OidcToken
        {
            get => _oidcToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oidcToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
        /// </summary>
        [Input("oidcTokenFilePath")]
        public Input<string>? OidcTokenFilePath { get; set; }

        /// <summary>
        /// The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
        /// </summary>
        [Input("resourceGroupName")]
        public Input<string>? ResourceGroupName { get; set; }

        [Input("sasToken")]
        private Input<string>? _sasToken;

        /// <summary>
        /// A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
        /// </summary>
        public Input<string>? SasToken
        {
            get => _sasToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sasToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The name of the storage account.
        /// </summary>
        [Input("storageAccountName", required: true)]
        public Input<string> StorageAccountName { get; set; } = null!;

        /// <summary>
        /// The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
        /// </summary>
        [Input("subscriptionId")]
        public Input<string>? SubscriptionId { get; set; }

        /// <summary>
        /// The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
        /// </summary>
        [Input("useAzureadAuth")]
        public Input<bool>? UseAzureadAuth { get; set; }

        /// <summary>
        /// Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
        /// </summary>
        [Input("useMsi")]
        public Input<bool>? UseMsi { get; set; }

        /// <summary>
        /// Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
        /// </summary>
        [Input("useOidc")]
        public Input<bool>? UseOidc { get; set; }

        /// <summary>
        /// The Terraform workspace to read state from.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        public GetAzureRMReferenceInvokeArgs()
        {
            Workspace = "default";
        }
        public static new GetAzureRMReferenceInvokeArgs Empty => new GetAzureRMReferenceInvokeArgs();
    }


    [OutputType]
    public sealed class GetAzureRMReferenceResult
    {
        /// <summary>
        /// The outputs displayed from Terraform state.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Outputs;

        [OutputConstructor]
        private GetAzureRMReferenceResult(ImmutableDictionary<string, object> outputs)
        {
            Outputs = outputs;
        }
    }
}
