// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Terraform.State
{
    public static class GetLocalReference
    {
        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Task<GetLocalReferenceResult> InvokeAsync(GetLocalReferenceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLocalReferenceResult>("terraform:state:getLocalReference", args ?? new GetLocalReferenceArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Output<GetLocalReferenceResult> Invoke(GetLocalReferenceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLocalReferenceResult>("terraform:state:getLocalReference", args ?? new GetLocalReferenceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from the local filesystem.
        /// </summary>
        public static Output<GetLocalReferenceResult> Invoke(GetLocalReferenceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetLocalReferenceResult>("terraform:state:getLocalReference", args ?? new GetLocalReferenceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLocalReferenceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
        /// </summary>
        [Input("path")]
        public string? Path { get; set; }

        /// <summary>
        /// The path to non-default workspaces.
        /// </summary>
        [Input("workspaceDir")]
        public string? WorkspaceDir { get; set; }

        public GetLocalReferenceArgs()
        {
        }
        public static new GetLocalReferenceArgs Empty => new GetLocalReferenceArgs();
    }

    public sealed class GetLocalReferenceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The path to the tfstate file. This defaults to "terraform.tfstate" relative to the root module by default.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// The path to non-default workspaces.
        /// </summary>
        [Input("workspaceDir")]
        public Input<string>? WorkspaceDir { get; set; }

        public GetLocalReferenceInvokeArgs()
        {
        }
        public static new GetLocalReferenceInvokeArgs Empty => new GetLocalReferenceInvokeArgs();
    }


    [OutputType]
    public sealed class GetLocalReferenceResult
    {
        /// <summary>
        /// The outputs displayed from Terraform state.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Outputs;

        [OutputConstructor]
        private GetLocalReferenceResult(ImmutableDictionary<string, object> outputs)
        {
            Outputs = outputs;
        }
    }
}
