// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Terraform.State
{
    public static class GetS3Reference
    {
        /// <summary>
        /// Access state from an AWS S3 bucket.
        /// </summary>
        public static Task<GetS3ReferenceResult> InvokeAsync(GetS3ReferenceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetS3ReferenceResult>("terraform:state:getS3Reference", args ?? new GetS3ReferenceArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from an AWS S3 bucket.
        /// </summary>
        public static Output<GetS3ReferenceResult> Invoke(GetS3ReferenceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetS3ReferenceResult>("terraform:state:getS3Reference", args ?? new GetS3ReferenceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Access state from an AWS S3 bucket.
        /// </summary>
        public static Output<GetS3ReferenceResult> Invoke(GetS3ReferenceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetS3ReferenceResult>("terraform:state:getS3Reference", args ?? new GetS3ReferenceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetS3ReferenceArgs : global::Pulumi.InvokeArgs
    {
        [Input("accessKey")]
        private string? _accessKey;

        /// <summary>
        /// AWS access key.
        /// </summary>
        public string? AccessKey
        {
            get => _accessKey;
            set => _accessKey = value;
        }

        /// <summary>
        /// The name of the S3 bucket.
        /// </summary>
        [Input("bucket", required: true)]
        public string Bucket { get; set; } = null!;

        /// <summary>
        /// Whether to enable server side encryption of the state file.
        /// </summary>
        [Input("encrypt")]
        public bool? Encrypt { get; set; }

        /// <summary>
        /// A custom endpoint for the S3 API.
        /// </summary>
        [Input("endpoint")]
        public string? Endpoint { get; set; }

        /// <summary>
        /// Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
        /// </summary>
        [Input("forcePathStyle")]
        public bool? ForcePathStyle { get; set; }

        /// <summary>
        /// A custom endpoint for the IAM API.
        /// </summary>
        [Input("iamEndpoint")]
        public string? IamEndpoint { get; set; }

        /// <summary>
        /// The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// The ARN of a KMS Key to use for encrypting the state.
        /// </summary>
        [Input("kmsKeyId")]
        public string? KmsKeyId { get; set; }

        /// <summary>
        /// The maximum number of times an AWS API request is retried on retryable failure.
        /// </summary>
        [Input("maxRetries")]
        public int? MaxRetries { get; set; }

        /// <summary>
        /// AWS profile name as set in the shared credentials file.
        /// </summary>
        [Input("profile")]
        public string? Profile { get; set; }

        /// <summary>
        /// AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        [Input("secretKey")]
        private string? _secretKey;

        /// <summary>
        /// AWS secret key.
        /// </summary>
        public string? SecretKey
        {
            get => _secretKey;
            set => _secretKey = value;
        }

        /// <summary>
        /// Path to a shared credentials file.
        /// </summary>
        [Input("sharedCredentialsFile")]
        public string? SharedCredentialsFile { get; set; }

        /// <summary>
        /// Skip the credentials validation via the STS API.
        /// </summary>
        [Input("skipCredentialsValidation")]
        public bool? SkipCredentialsValidation { get; set; }

        /// <summary>
        /// Skip the AWS Metadata API check.
        /// </summary>
        [Input("skipMetadataApiCheck")]
        public bool? SkipMetadataApiCheck { get; set; }

        /// <summary>
        /// Skip static validation of region name.
        /// </summary>
        [Input("skipRegionValidation")]
        public bool? SkipRegionValidation { get; set; }

        [Input("sseCustomerKey")]
        private string? _sseCustomerKey;

        /// <summary>
        /// The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
        /// </summary>
        public string? SseCustomerKey
        {
            get => _sseCustomerKey;
            set => _sseCustomerKey = value;
        }

        /// <summary>
        /// A custom endpoint for the STS API.
        /// </summary>
        [Input("stsEndpoint")]
        public string? StsEndpoint { get; set; }

        [Input("token")]
        private string? _token;

        /// <summary>
        /// AWS session token.
        /// </summary>
        public string? Token
        {
            get => _token;
            set => _token = value;
        }

        /// <summary>
        /// The Terraform workspace to read state from.
        /// </summary>
        [Input("workspace")]
        public string? Workspace { get; set; }

        /// <summary>
        /// The prefix applied to the non-default state path inside the bucket.
        /// </summary>
        [Input("workspaceKeyPrefix")]
        public string? WorkspaceKeyPrefix { get; set; }

        public GetS3ReferenceArgs()
        {
            Workspace = "default";
        }
        public static new GetS3ReferenceArgs Empty => new GetS3ReferenceArgs();
    }

    public sealed class GetS3ReferenceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accessKey")]
        private Input<string>? _accessKey;

        /// <summary>
        /// AWS access key.
        /// </summary>
        public Input<string>? AccessKey
        {
            get => _accessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The name of the S3 bucket.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        /// <summary>
        /// Whether to enable server side encryption of the state file.
        /// </summary>
        [Input("encrypt")]
        public Input<bool>? Encrypt { get; set; }

        /// <summary>
        /// A custom endpoint for the S3 API.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
        /// </summary>
        [Input("forcePathStyle")]
        public Input<bool>? ForcePathStyle { get; set; }

        /// <summary>
        /// A custom endpoint for the IAM API.
        /// </summary>
        [Input("iamEndpoint")]
        public Input<string>? IamEndpoint { get; set; }

        /// <summary>
        /// The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The ARN of a KMS Key to use for encrypting the state.
        /// </summary>
        [Input("kmsKeyId")]
        public Input<string>? KmsKeyId { get; set; }

        /// <summary>
        /// The maximum number of times an AWS API request is retried on retryable failure.
        /// </summary>
        [Input("maxRetries")]
        public Input<int>? MaxRetries { get; set; }

        /// <summary>
        /// AWS profile name as set in the shared credentials file.
        /// </summary>
        [Input("profile")]
        public Input<string>? Profile { get; set; }

        /// <summary>
        /// AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("secretKey")]
        private Input<string>? _secretKey;

        /// <summary>
        /// AWS secret key.
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Path to a shared credentials file.
        /// </summary>
        [Input("sharedCredentialsFile")]
        public Input<string>? SharedCredentialsFile { get; set; }

        /// <summary>
        /// Skip the credentials validation via the STS API.
        /// </summary>
        [Input("skipCredentialsValidation")]
        public Input<bool>? SkipCredentialsValidation { get; set; }

        /// <summary>
        /// Skip the AWS Metadata API check.
        /// </summary>
        [Input("skipMetadataApiCheck")]
        public Input<bool>? SkipMetadataApiCheck { get; set; }

        /// <summary>
        /// Skip static validation of region name.
        /// </summary>
        [Input("skipRegionValidation")]
        public Input<bool>? SkipRegionValidation { get; set; }

        [Input("sseCustomerKey")]
        private Input<string>? _sseCustomerKey;

        /// <summary>
        /// The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
        /// </summary>
        public Input<string>? SseCustomerKey
        {
            get => _sseCustomerKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sseCustomerKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// A custom endpoint for the STS API.
        /// </summary>
        [Input("stsEndpoint")]
        public Input<string>? StsEndpoint { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// AWS session token.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The Terraform workspace to read state from.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        /// <summary>
        /// The prefix applied to the non-default state path inside the bucket.
        /// </summary>
        [Input("workspaceKeyPrefix")]
        public Input<string>? WorkspaceKeyPrefix { get; set; }

        public GetS3ReferenceInvokeArgs()
        {
            Workspace = "default";
        }
        public static new GetS3ReferenceInvokeArgs Empty => new GetS3ReferenceInvokeArgs();
    }


    [OutputType]
    public sealed class GetS3ReferenceResult
    {
        /// <summary>
        /// The outputs displayed from Terraform state.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Outputs;

        [OutputConstructor]
        private GetS3ReferenceResult(ImmutableDictionary<string, object> outputs)
        {
            Outputs = outputs;
        }
    }
}
