#!/bin/bash
set -o nounset -o errexit -o pipefail

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NPM_VERSION="$($SCRIPT_ROOT/get-version "$@")"

if [ "${GO}" == "" ]; then
	GO=go
fi

${GO} run "${SCRIPT_ROOT}/get-py-version.go" "${NPM_VERSION}"
