// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Access state stored in an Azure Blob Storage container.
 */
export function getAzureRMReference(args: GetAzureRMReferenceArgs, opts?: pulumi.InvokeOptions): Promise<GetAzureRMReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("terraform:state:getAzureRMReference", {
        "accessKey": args.accessKey,
        "clientCertificatePassword": args.clientCertificatePassword,
        "clientCertificatePath": args.clientCertificatePath,
        "clientId": args.clientId,
        "clientSecret": args.clientSecret,
        "containerName": args.containerName,
        "endpoint": args.endpoint,
        "environment": args.environment,
        "key": args.key,
        "metadataHost": args.metadataHost,
        "msiEndpoint": args.msiEndpoint,
        "oidcRequestToken": args.oidcRequestToken,
        "oidcRequestUrl": args.oidcRequestUrl,
        "oidcToken": args.oidcToken,
        "oidcTokenFilePath": args.oidcTokenFilePath,
        "resourceGroupName": args.resourceGroupName,
        "sasToken": args.sasToken,
        "storageAccountName": args.storageAccountName,
        "subscriptionId": args.subscriptionId,
        "tenantId": args.tenantId,
        "useAzureadAuth": args.useAzureadAuth,
        "useMsi": args.useMsi,
        "useOidc": args.useOidc,
        "workspace": (args.workspace) ?? "default",
    }, opts);
}

export interface GetAzureRMReferenceArgs {
    /**
     * The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
     */
    accessKey?: string;
    /**
     * The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
     */
    clientCertificatePassword?: string;
    /**
     * The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
     */
    clientCertificatePath?: string;
    /**
     * The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
     */
    clientId?: string;
    /**
     * The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
     */
    clientSecret?: string;
    /**
     * The name of the storage container within the storage account.
     */
    containerName: string;
    /**
     * A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
     */
    endpoint?: string;
    /**
     * The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
     */
    environment?: string;
    /**
     * The name of the blob holding the Terraform state file inside the storage container.
     */
    key: string;
    /**
     * The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
     */
    metadataHost?: string;
    /**
     * The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
     */
    msiEndpoint?: string;
    /**
     * The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
     */
    oidcRequestToken?: string;
    /**
     * The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
     */
    oidcRequestUrl?: string;
    /**
     * A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
     */
    oidcToken?: string;
    /**
     * The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
     */
    oidcTokenFilePath?: string;
    /**
     * The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
     */
    resourceGroupName?: string;
    /**
     * A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
     */
    sasToken?: string;
    /**
     * The name of the storage account.
     */
    storageAccountName: string;
    /**
     * The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
     */
    subscriptionId?: string;
    /**
     * The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
     */
    tenantId?: string;
    /**
     * Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
     */
    useAzureadAuth?: boolean;
    /**
     * Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
     */
    useMsi?: boolean;
    /**
     * Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
     */
    useOidc?: boolean;
    /**
     * The Terraform workspace to read state from.
     */
    workspace?: string;
}

/**
 * The result of fetching from a Terraform state store.
 */
export interface GetAzureRMReferenceResult {
    /**
     * The outputs displayed from Terraform state.
     */
    readonly outputs: {[key: string]: any};
}
/**
 * Access state stored in an Azure Blob Storage container.
 */
export function getAzureRMReferenceOutput(args: GetAzureRMReferenceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAzureRMReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("terraform:state:getAzureRMReference", {
        "accessKey": args.accessKey,
        "clientCertificatePassword": args.clientCertificatePassword,
        "clientCertificatePath": args.clientCertificatePath,
        "clientId": args.clientId,
        "clientSecret": args.clientSecret,
        "containerName": args.containerName,
        "endpoint": args.endpoint,
        "environment": args.environment,
        "key": args.key,
        "metadataHost": args.metadataHost,
        "msiEndpoint": args.msiEndpoint,
        "oidcRequestToken": args.oidcRequestToken,
        "oidcRequestUrl": args.oidcRequestUrl,
        "oidcToken": args.oidcToken,
        "oidcTokenFilePath": args.oidcTokenFilePath,
        "resourceGroupName": args.resourceGroupName,
        "sasToken": args.sasToken,
        "storageAccountName": args.storageAccountName,
        "subscriptionId": args.subscriptionId,
        "tenantId": args.tenantId,
        "useAzureadAuth": args.useAzureadAuth,
        "useMsi": args.useMsi,
        "useOidc": args.useOidc,
        "workspace": (args.workspace) ?? "default",
    }, opts);
}

export interface GetAzureRMReferenceOutputArgs {
    /**
     * The access key of the storage account. Falls back to the ARM_ACCESS_KEY environment variable when unset.
     */
    accessKey?: pulumi.Input<string | undefined>;
    /**
     * The password for the client certificate specified in clientCertificatePath. Falls back to the ARM_CLIENT_CERTIFICATE_PASSWORD environment variable when unset.
     */
    clientCertificatePassword?: pulumi.Input<string | undefined>;
    /**
     * The path to the PFX file used as the client certificate for service principal authentication. Falls back to the ARM_CLIENT_CERTIFICATE_PATH environment variable when unset.
     */
    clientCertificatePath?: pulumi.Input<string | undefined>;
    /**
     * The client ID to authenticate as. Falls back to the ARM_CLIENT_ID environment variable when unset.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The client secret used for service principal authentication. Falls back to the ARM_CLIENT_SECRET environment variable when unset.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * The name of the storage container within the storage account.
     */
    containerName: pulumi.Input<string>;
    /**
     * A custom endpoint for the Azure Resource Manager API. Falls back to the ARM_ENDPOINT environment variable when unset.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * The Azure cloud environment to use: public (default), china, german, stack or usgovernment. Falls back to the ARM_ENVIRONMENT environment variable when unset.
     */
    environment?: pulumi.Input<string | undefined>;
    /**
     * The name of the blob holding the Terraform state file inside the storage container.
     */
    key: pulumi.Input<string>;
    /**
     * The hostname of the Azure metadata service used to obtain the cloud environment. Falls back to the ARM_METADATA_HOST environment variable when unset.
     */
    metadataHost?: pulumi.Input<string | undefined>;
    /**
     * The endpoint of the Managed Service Identity. Falls back to the ARM_MSI_ENDPOINT environment variable when unset.
     */
    msiEndpoint?: pulumi.Input<string | undefined>;
    /**
     * The bearer token for requests to the oidcRequestUrl URL. Falls back to the ARM_OIDC_REQUEST_TOKEN or ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables when unset.
     */
    oidcRequestToken?: pulumi.Input<string | undefined>;
    /**
     * The URL of the OIDC provider to request an ID token from, e.g. in GitHub Actions. Requires oidcRequestToken. Falls back to the ARM_OIDC_REQUEST_URL or ACTIONS_ID_TOKEN_REQUEST_URL environment variables when unset.
     */
    oidcRequestUrl?: pulumi.Input<string | undefined>;
    /**
     * A JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN environment variable when unset.
     */
    oidcToken?: pulumi.Input<string | undefined>;
    /**
     * The path to a file containing a JWT token for OIDC authentication. Conflicts with oidcRequestToken. Falls back to the ARM_OIDC_TOKEN_FILE_PATH environment variable when unset.
     */
    oidcTokenFilePath?: pulumi.Input<string | undefined>;
    /**
     * The name of the resource group holding the storage account. Required when using AzureAD authentication against the Azure Resource Manager API to look up the storage access key.
     */
    resourceGroupName?: pulumi.Input<string | undefined>;
    /**
     * A SAS token for accessing the storage container. Falls back to the ARM_SAS_TOKEN environment variable when unset.
     */
    sasToken?: pulumi.Input<string | undefined>;
    /**
     * The name of the storage account.
     */
    storageAccountName: pulumi.Input<string>;
    /**
     * The subscription ID holding the storage account. Falls back to the ARM_SUBSCRIPTION_ID environment variable when unset.
     */
    subscriptionId?: pulumi.Input<string | undefined>;
    /**
     * The tenant ID to authenticate against. Falls back to the ARM_TENANT_ID environment variable when unset.
     */
    tenantId?: pulumi.Input<string | undefined>;
    /**
     * Whether to authenticate against the storage container with AzureAD instead of an access key. Falls back to the ARM_USE_AZUREAD environment variable when unset.
     */
    useAzureadAuth?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to authenticate using Managed Service Identity. Falls back to the ARM_USE_MSI environment variable when unset.
     */
    useMsi?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to authenticate using OIDC. Falls back to the ARM_USE_OIDC environment variable when unset.
     */
    useOidc?: pulumi.Input<boolean | undefined>;
    /**
     * The Terraform workspace to read state from.
     */
    workspace?: pulumi.Input<string | undefined>;
}
