// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Access state from a remote backend.
 */
export function getRemoteReference(args: GetRemoteReferenceArgs, opts?: pulumi.InvokeOptions): Promise<GetRemoteReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("terraform:state:getRemoteReference", {
        "hostname": args.hostname,
        "organization": args.organization,
        "token": args.token,
        "workspaces": args.workspaces,
    }, opts);
}

export interface GetRemoteReferenceArgs {
    /**
     * The remote backend hostname to connect to.
     */
    hostname?: string;
    /**
     * The name of the organization containing the targeted workspace(s).
     */
    organization: string;
    /**
     * The token used to authenticate with the remote backend.
     */
    token?: string;
    workspaces: inputs.state.Workspaces;
}

/**
 * The result of fetching from a Terraform state store.
 */
export interface GetRemoteReferenceResult {
    /**
     * The outputs displayed from Terraform state.
     */
    readonly outputs: {[key: string]: any};
}
/**
 * Access state from a remote backend.
 */
export function getRemoteReferenceOutput(args: GetRemoteReferenceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRemoteReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("terraform:state:getRemoteReference", {
        "hostname": args.hostname,
        "organization": args.organization,
        "token": args.token,
        "workspaces": args.workspaces,
    }, opts);
}

export interface GetRemoteReferenceOutputArgs {
    /**
     * The remote backend hostname to connect to.
     */
    hostname?: pulumi.Input<string>;
    /**
     * The name of the organization containing the targeted workspace(s).
     */
    organization: pulumi.Input<string>;
    /**
     * The token used to authenticate with the remote backend.
     */
    token?: pulumi.Input<string>;
    workspaces: pulumi.Input<inputs.state.WorkspacesArgs>;
}
