// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Access state from an AWS S3 bucket.
 */
export function getS3Reference(args: GetS3ReferenceArgs, opts?: pulumi.InvokeOptions): Promise<GetS3ReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("terraform:state:getS3Reference", {
        "accessKey": args.accessKey,
        "bucket": args.bucket,
        "encrypt": args.encrypt,
        "endpoint": args.endpoint,
        "forcePathStyle": args.forcePathStyle,
        "iamEndpoint": args.iamEndpoint,
        "key": args.key,
        "kmsKeyId": args.kmsKeyId,
        "maxRetries": args.maxRetries,
        "profile": args.profile,
        "region": args.region,
        "secretKey": args.secretKey,
        "sharedCredentialsFile": args.sharedCredentialsFile,
        "skipCredentialsValidation": args.skipCredentialsValidation,
        "skipMetadataApiCheck": args.skipMetadataApiCheck,
        "skipRegionValidation": args.skipRegionValidation,
        "sseCustomerKey": args.sseCustomerKey,
        "stsEndpoint": args.stsEndpoint,
        "token": args.token,
        "workspace": args.workspace,
        "workspaceKeyPrefix": args.workspaceKeyPrefix,
    }, opts);
}

export interface GetS3ReferenceArgs {
    /**
     * AWS access key.
     */
    accessKey?: string;
    /**
     * The name of the S3 bucket.
     */
    bucket: string;
    /**
     * Whether to enable server side encryption of the state file.
     */
    encrypt?: boolean;
    /**
     * A custom endpoint for the S3 API.
     */
    endpoint?: string;
    /**
     * Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     */
    forcePathStyle?: boolean;
    /**
     * A custom endpoint for the IAM API.
     */
    iamEndpoint?: string;
    /**
     * The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     */
    key: string;
    /**
     * The ARN of a KMS Key to use for encrypting the state.
     */
    kmsKeyId?: string;
    /**
     * The maximum number of times an AWS API request is retried on retryable failure.
     */
    maxRetries?: number;
    /**
     * AWS profile name as set in the shared credentials file.
     */
    profile?: string;
    /**
     * AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     */
    region?: string;
    /**
     * AWS secret key.
     */
    secretKey?: string;
    /**
     * Path to a shared credentials file.
     */
    sharedCredentialsFile?: string;
    /**
     * Skip the credentials validation via the STS API.
     */
    skipCredentialsValidation?: boolean;
    /**
     * Skip the AWS Metadata API check.
     */
    skipMetadataApiCheck?: boolean;
    /**
     * Skip static validation of region name.
     */
    skipRegionValidation?: boolean;
    /**
     * The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     */
    sseCustomerKey?: string;
    /**
     * A custom endpoint for the STS API.
     */
    stsEndpoint?: string;
    /**
     * AWS session token.
     */
    token?: string;
    /**
     * The Terraform workspace to read state from.
     */
    workspace?: string;
    /**
     * The prefix applied to the non-default state path inside the bucket.
     */
    workspaceKeyPrefix?: string;
}

/**
 * The result of fetching from a Terraform state store.
 */
export interface GetS3ReferenceResult {
    /**
     * The outputs displayed from Terraform state.
     */
    readonly outputs: {[key: string]: any};
}
/**
 * Access state from an AWS S3 bucket.
 */
export function getS3ReferenceOutput(args: GetS3ReferenceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetS3ReferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("terraform:state:getS3Reference", {
        "accessKey": args.accessKey,
        "bucket": args.bucket,
        "encrypt": args.encrypt,
        "endpoint": args.endpoint,
        "forcePathStyle": args.forcePathStyle,
        "iamEndpoint": args.iamEndpoint,
        "key": args.key,
        "kmsKeyId": args.kmsKeyId,
        "maxRetries": args.maxRetries,
        "profile": args.profile,
        "region": args.region,
        "secretKey": args.secretKey,
        "sharedCredentialsFile": args.sharedCredentialsFile,
        "skipCredentialsValidation": args.skipCredentialsValidation,
        "skipMetadataApiCheck": args.skipMetadataApiCheck,
        "skipRegionValidation": args.skipRegionValidation,
        "sseCustomerKey": args.sseCustomerKey,
        "stsEndpoint": args.stsEndpoint,
        "token": args.token,
        "workspace": args.workspace,
        "workspaceKeyPrefix": args.workspaceKeyPrefix,
    }, opts);
}

export interface GetS3ReferenceOutputArgs {
    /**
     * AWS access key.
     */
    accessKey?: pulumi.Input<string>;
    /**
     * The name of the S3 bucket.
     */
    bucket: pulumi.Input<string>;
    /**
     * Whether to enable server side encryption of the state file.
     */
    encrypt?: pulumi.Input<boolean>;
    /**
     * A custom endpoint for the S3 API.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Force s3 to use path-style addressing instead of virtual hosted-bucket addressing. Required by most S3-compatible stores.
     */
    forcePathStyle?: pulumi.Input<boolean>;
    /**
     * A custom endpoint for the IAM API.
     */
    iamEndpoint?: pulumi.Input<string>;
    /**
     * The path to the state file inside the bucket. When using a non-default workspace, the state path is /workspace_key_prefix/workspace_name/key.
     */
    key: pulumi.Input<string>;
    /**
     * The ARN of a KMS Key to use for encrypting the state.
     */
    kmsKeyId?: pulumi.Input<string>;
    /**
     * The maximum number of times an AWS API request is retried on retryable failure.
     */
    maxRetries?: pulumi.Input<number>;
    /**
     * AWS profile name as set in the shared credentials file.
     */
    profile?: pulumi.Input<string>;
    /**
     * AWS region of the S3 bucket. Falls back to the AWS_REGION or AWS_DEFAULT_REGION environment variables when unset.
     */
    region?: pulumi.Input<string>;
    /**
     * AWS secret key.
     */
    secretKey?: pulumi.Input<string>;
    /**
     * Path to a shared credentials file.
     */
    sharedCredentialsFile?: pulumi.Input<string>;
    /**
     * Skip the credentials validation via the STS API.
     */
    skipCredentialsValidation?: pulumi.Input<boolean>;
    /**
     * Skip the AWS Metadata API check.
     */
    skipMetadataApiCheck?: pulumi.Input<boolean>;
    /**
     * Skip static validation of region name.
     */
    skipRegionValidation?: pulumi.Input<boolean>;
    /**
     * The base64-encoded encryption key to use for server-side encryption with customer-provided keys (SSE-C).
     */
    sseCustomerKey?: pulumi.Input<string>;
    /**
     * A custom endpoint for the STS API.
     */
    stsEndpoint?: pulumi.Input<string>;
    /**
     * AWS session token.
     */
    token?: pulumi.Input<string>;
    /**
     * The Terraform workspace to read state from.
     */
    workspace?: pulumi.Input<string>;
    /**
     * The prefix applied to the non-default state path inside the bucket.
     */
    workspaceKeyPrefix?: pulumi.Input<string>;
}
