// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { GetLocalReferenceArgs, GetLocalReferenceResult, GetLocalReferenceOutputArgs } from "./getLocalReference";
export const getLocalReference: typeof import("./getLocalReference").getLocalReference = null as any;
export const getLocalReferenceOutput: typeof import("./getLocalReference").getLocalReferenceOutput = null as any;
utilities.lazyLoad(exports, ["getLocalReference","getLocalReferenceOutput"], () => require("./getLocalReference"));

export { GetRemoteReferenceArgs, GetRemoteReferenceResult, GetRemoteReferenceOutputArgs } from "./getRemoteReference";
export const getRemoteReference: typeof import("./getRemoteReference").getRemoteReference = null as any;
export const getRemoteReferenceOutput: typeof import("./getRemoteReference").getRemoteReferenceOutput = null as any;
utilities.lazyLoad(exports, ["getRemoteReference","getRemoteReferenceOutput"], () => require("./getRemoteReference"));

