// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace state {
    export interface Workspaces {
        /**
         * The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
         */
        name?: string;
        /**
         * A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in HCP Terraform, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
         */
        prefix?: string;
    }

    export interface WorkspacesArgs {
        /**
         * The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
         */
        name?: pulumi.Input<string>;
        /**
         * A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in HCP Terraform, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
         */
        prefix?: pulumi.Input<string>;
    }
}
