// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.terraform.state;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.terraform.Utilities;
import com.pulumi.terraform.state.inputs.GetLocalReferenceArgs;
import com.pulumi.terraform.state.inputs.GetLocalReferencePlainArgs;
import com.pulumi.terraform.state.inputs.GetRemoteReferenceArgs;
import com.pulumi.terraform.state.inputs.GetRemoteReferencePlainArgs;
import com.pulumi.terraform.state.outputs.GetLocalReferenceResult;
import com.pulumi.terraform.state.outputs.GetRemoteReferenceResult;
import java.util.concurrent.CompletableFuture;

public final class StateFunctions {
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<GetLocalReferenceResult> getLocalReference() {
        return getLocalReference(GetLocalReferenceArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<GetLocalReferenceResult> getLocalReferencePlain() {
        return getLocalReferencePlain(GetLocalReferencePlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<GetLocalReferenceResult> getLocalReference(GetLocalReferenceArgs args) {
        return getLocalReference(args, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<GetLocalReferenceResult> getLocalReferencePlain(GetLocalReferencePlainArgs args) {
        return getLocalReferencePlain(args, InvokeOptions.Empty);
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<GetLocalReferenceResult> getLocalReference(GetLocalReferenceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("terraform:state:getLocalReference", TypeShape.of(GetLocalReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static Output<GetLocalReferenceResult> getLocalReference(GetLocalReferenceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("terraform:state:getLocalReference", TypeShape.of(GetLocalReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from the local filesystem.
     * 
     */
    public static CompletableFuture<GetLocalReferenceResult> getLocalReferencePlain(GetLocalReferencePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("terraform:state:getLocalReference", TypeShape.of(GetLocalReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<GetRemoteReferenceResult> getRemoteReference(GetRemoteReferenceArgs args) {
        return getRemoteReference(args, InvokeOptions.Empty);
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static CompletableFuture<GetRemoteReferenceResult> getRemoteReferencePlain(GetRemoteReferencePlainArgs args) {
        return getRemoteReferencePlain(args, InvokeOptions.Empty);
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<GetRemoteReferenceResult> getRemoteReference(GetRemoteReferenceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("terraform:state:getRemoteReference", TypeShape.of(GetRemoteReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static Output<GetRemoteReferenceResult> getRemoteReference(GetRemoteReferenceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("terraform:state:getRemoteReference", TypeShape.of(GetRemoteReferenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Access state from a remote backend.
     * 
     */
    public static CompletableFuture<GetRemoteReferenceResult> getRemoteReferencePlain(GetRemoteReferencePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("terraform:state:getRemoteReference", TypeShape.of(GetRemoteReferenceResult.class), args, Utilities.withVersion(options));
    }
}
